//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FlywaySchemaHistory = newFlywaySchemaHistoryTable("db_crocs", "flyway_schema_history", "")

type flywaySchemaHistoryTable struct {
	mysql.Table

	// Columns
	InstalledRank mysql.ColumnInteger
	Version       mysql.ColumnString
	Description   mysql.ColumnString
	Type          mysql.ColumnString
	Script        mysql.ColumnString
	Checksum      mysql.ColumnInteger
	InstalledBy   mysql.ColumnString
	InstalledOn   mysql.ColumnTimestamp
	ExecutionTime mysql.ColumnInteger
	Success       mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FlywaySchemaHistoryTable struct {
	flywaySchemaHistoryTable

	NEW flywaySchemaHistoryTable
}

// AS creates new FlywaySchemaHistoryTable with assigned alias
func (a FlywaySchemaHistoryTable) AS(alias string) *FlywaySchemaHistoryTable {
	return newFlywaySchemaHistoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FlywaySchemaHistoryTable with assigned schema name
func (a FlywaySchemaHistoryTable) FromSchema(schemaName string) *FlywaySchemaHistoryTable {
	return newFlywaySchemaHistoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FlywaySchemaHistoryTable with assigned table prefix
func (a FlywaySchemaHistoryTable) WithPrefix(prefix string) *FlywaySchemaHistoryTable {
	return newFlywaySchemaHistoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FlywaySchemaHistoryTable with assigned table suffix
func (a FlywaySchemaHistoryTable) WithSuffix(suffix string) *FlywaySchemaHistoryTable {
	return newFlywaySchemaHistoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFlywaySchemaHistoryTable(schemaName, tableName, alias string) *FlywaySchemaHistoryTable {
	return &FlywaySchemaHistoryTable{
		flywaySchemaHistoryTable: newFlywaySchemaHistoryTableImpl(schemaName, tableName, alias),
		NEW:                      newFlywaySchemaHistoryTableImpl("", "new", ""),
	}
}

func newFlywaySchemaHistoryTableImpl(schemaName, tableName, alias string) flywaySchemaHistoryTable {
	var (
		InstalledRankColumn = mysql.IntegerColumn("installed_rank")
		VersionColumn       = mysql.StringColumn("version")
		DescriptionColumn   = mysql.StringColumn("description")
		TypeColumn          = mysql.StringColumn("type")
		ScriptColumn        = mysql.StringColumn("script")
		ChecksumColumn      = mysql.IntegerColumn("checksum")
		InstalledByColumn   = mysql.StringColumn("installed_by")
		InstalledOnColumn   = mysql.TimestampColumn("installed_on")
		ExecutionTimeColumn = mysql.IntegerColumn("execution_time")
		SuccessColumn       = mysql.BoolColumn("success")
		allColumns          = mysql.ColumnList{InstalledRankColumn, VersionColumn, DescriptionColumn, TypeColumn, ScriptColumn, ChecksumColumn, InstalledByColumn, InstalledOnColumn, ExecutionTimeColumn, SuccessColumn}
		mutableColumns      = mysql.ColumnList{VersionColumn, DescriptionColumn, TypeColumn, ScriptColumn, ChecksumColumn, InstalledByColumn, InstalledOnColumn, ExecutionTimeColumn, SuccessColumn}
		defaultColumns      = mysql.ColumnList{InstalledOnColumn}
	)

	return flywaySchemaHistoryTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		InstalledRank: InstalledRankColumn,
		Version:       VersionColumn,
		Description:   DescriptionColumn,
		Type:          TypeColumn,
		Script:        ScriptColumn,
		Checksum:      ChecksumColumn,
		InstalledBy:   InstalledByColumn,
		InstalledOn:   InstalledOnColumn,
		ExecutionTime: ExecutionTimeColumn,
		Success:       SuccessColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
