//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Posts = newPostsTable("db_crocs", "posts", "")

type postsTable struct {
	mysql.Table

	// Columns
	PostID        mysql.ColumnString
	PostProjectID mysql.ColumnString
	Content       mysql.ColumnString
	Visibility    mysql.ColumnString
	CreatedTime   mysql.ColumnTimestamp
	UpdatedTime   mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type PostsTable struct {
	postsTable

	NEW postsTable
}

// AS creates new PostsTable with assigned alias
func (a PostsTable) AS(alias string) *PostsTable {
	return newPostsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PostsTable with assigned schema name
func (a PostsTable) FromSchema(schemaName string) *PostsTable {
	return newPostsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PostsTable with assigned table prefix
func (a PostsTable) WithPrefix(prefix string) *PostsTable {
	return newPostsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PostsTable with assigned table suffix
func (a PostsTable) WithSuffix(suffix string) *PostsTable {
	return newPostsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPostsTable(schemaName, tableName, alias string) *PostsTable {
	return &PostsTable{
		postsTable: newPostsTableImpl(schemaName, tableName, alias),
		NEW:        newPostsTableImpl("", "new", ""),
	}
}

func newPostsTableImpl(schemaName, tableName, alias string) postsTable {
	var (
		PostIDColumn        = mysql.StringColumn("post_id")
		PostProjectIDColumn = mysql.StringColumn("post_project_id")
		ContentColumn       = mysql.StringColumn("content")
		VisibilityColumn    = mysql.StringColumn("visibility")
		CreatedTimeColumn   = mysql.TimestampColumn("created_time")
		UpdatedTimeColumn   = mysql.TimestampColumn("updated_time")
		allColumns          = mysql.ColumnList{PostIDColumn, PostProjectIDColumn, ContentColumn, VisibilityColumn, CreatedTimeColumn, UpdatedTimeColumn}
		mutableColumns      = mysql.ColumnList{ContentColumn, VisibilityColumn, CreatedTimeColumn, UpdatedTimeColumn}
		defaultColumns      = mysql.ColumnList{CreatedTimeColumn}
	)

	return postsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PostID:        PostIDColumn,
		PostProjectID: PostProjectIDColumn,
		Content:       ContentColumn,
		Visibility:    VisibilityColumn,
		CreatedTime:   CreatedTimeColumn,
		UpdatedTime:   UpdatedTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
