//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Projects = newProjectsTable("db_crocs", "projects", "")

type projectsTable struct {
	mysql.Table

	// Columns
	ProjectID      mysql.ColumnString
	ProjectUserID  mysql.ColumnString
	Name           mysql.ColumnString
	Description    mysql.ColumnString
	Thumbnail      mysql.ColumnString
	Location       mysql.ColumnString
	Cost           mysql.ColumnInteger
	StartDate      mysql.ColumnDate
	CompletionDate mysql.ColumnDate
	CreatedTime    mysql.ColumnTimestamp
	UpdatedTime    mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ProjectsTable struct {
	projectsTable

	NEW projectsTable
}

// AS creates new ProjectsTable with assigned alias
func (a ProjectsTable) AS(alias string) *ProjectsTable {
	return newProjectsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProjectsTable with assigned schema name
func (a ProjectsTable) FromSchema(schemaName string) *ProjectsTable {
	return newProjectsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProjectsTable with assigned table prefix
func (a ProjectsTable) WithPrefix(prefix string) *ProjectsTable {
	return newProjectsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProjectsTable with assigned table suffix
func (a ProjectsTable) WithSuffix(suffix string) *ProjectsTable {
	return newProjectsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProjectsTable(schemaName, tableName, alias string) *ProjectsTable {
	return &ProjectsTable{
		projectsTable: newProjectsTableImpl(schemaName, tableName, alias),
		NEW:           newProjectsTableImpl("", "new", ""),
	}
}

func newProjectsTableImpl(schemaName, tableName, alias string) projectsTable {
	var (
		ProjectIDColumn      = mysql.StringColumn("project_id")
		ProjectUserIDColumn  = mysql.StringColumn("project_user_id")
		NameColumn           = mysql.StringColumn("name")
		DescriptionColumn    = mysql.StringColumn("description")
		ThumbnailColumn      = mysql.StringColumn("thumbnail")
		LocationColumn       = mysql.StringColumn("location")
		CostColumn           = mysql.IntegerColumn("cost")
		StartDateColumn      = mysql.DateColumn("start_date")
		CompletionDateColumn = mysql.DateColumn("completion_date")
		CreatedTimeColumn    = mysql.TimestampColumn("created_time")
		UpdatedTimeColumn    = mysql.TimestampColumn("updated_time")
		allColumns           = mysql.ColumnList{ProjectIDColumn, ProjectUserIDColumn, NameColumn, DescriptionColumn, ThumbnailColumn, LocationColumn, CostColumn, StartDateColumn, CompletionDateColumn, CreatedTimeColumn, UpdatedTimeColumn}
		mutableColumns       = mysql.ColumnList{NameColumn, DescriptionColumn, ThumbnailColumn, LocationColumn, CostColumn, StartDateColumn, CompletionDateColumn, CreatedTimeColumn, UpdatedTimeColumn}
		defaultColumns       = mysql.ColumnList{CreatedTimeColumn}
	)

	return projectsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ProjectID:      ProjectIDColumn,
		ProjectUserID:  ProjectUserIDColumn,
		Name:           NameColumn,
		Description:    DescriptionColumn,
		Thumbnail:      ThumbnailColumn,
		Location:       LocationColumn,
		Cost:           CostColumn,
		StartDate:      StartDateColumn,
		CompletionDate: CompletionDateColumn,
		CreatedTime:    CreatedTimeColumn,
		UpdatedTime:    UpdatedTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
