//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Users = newUsersTable("db_crocs", "users", "")

type usersTable struct {
	mysql.Table

	// Columns
	UserID     mysql.ColumnString
	Email      mysql.ColumnString
	Gender     mysql.ColumnString
	ProfileURL mysql.ColumnString
	Nickname   mysql.ColumnString
	Username   mysql.ColumnString
	Password   mysql.ColumnString
	CreatedAt  mysql.ColumnTimestamp
	UpdatedAt  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type UsersTable struct {
	usersTable

	NEW usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersTable with assigned table prefix
func (a UsersTable) WithPrefix(prefix string) *UsersTable {
	return newUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersTable with assigned table suffix
func (a UsersTable) WithSuffix(suffix string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		NEW:        newUsersTableImpl("", "new", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		UserIDColumn     = mysql.StringColumn("user_id")
		EmailColumn      = mysql.StringColumn("email")
		GenderColumn     = mysql.StringColumn("gender")
		ProfileURLColumn = mysql.StringColumn("profile_url")
		NicknameColumn   = mysql.StringColumn("nickname")
		UsernameColumn   = mysql.StringColumn("username")
		PasswordColumn   = mysql.StringColumn("password")
		CreatedAtColumn  = mysql.TimestampColumn("created_at")
		UpdatedAtColumn  = mysql.TimestampColumn("updated_at")
		allColumns       = mysql.ColumnList{UserIDColumn, EmailColumn, GenderColumn, ProfileURLColumn, NicknameColumn, UsernameColumn, PasswordColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = mysql.ColumnList{EmailColumn, GenderColumn, ProfileURLColumn, NicknameColumn, UsernameColumn, PasswordColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = mysql.ColumnList{EmailColumn, GenderColumn, CreatedAtColumn}
	)

	return usersTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:     UserIDColumn,
		Email:      EmailColumn,
		Gender:     GenderColumn,
		ProfileURL: ProfileURLColumn,
		Nickname:   NicknameColumn,
		Username:   UsernameColumn,
		Password:   PasswordColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
