//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ChatThreadParticipants = newChatThreadParticipantsTable("db_crocs", "chat_thread_participants", "")

type chatThreadParticipantsTable struct {
	mysql.Table

	// Columns
	ChatThreadID      mysql.ColumnString
	UserID            mysql.ColumnString
	ArchivedAt        mysql.ColumnTimestamp
	MutedAt           mysql.ColumnTimestamp
	LastReadMessageID mysql.ColumnString
	LastReadAt        mysql.ColumnTimestamp
	JoinedAt          mysql.ColumnTimestamp
	LeftAt            mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ChatThreadParticipantsTable struct {
	chatThreadParticipantsTable

	NEW chatThreadParticipantsTable
}

// AS creates new ChatThreadParticipantsTable with assigned alias
func (a ChatThreadParticipantsTable) AS(alias string) *ChatThreadParticipantsTable {
	return newChatThreadParticipantsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ChatThreadParticipantsTable with assigned schema name
func (a ChatThreadParticipantsTable) FromSchema(schemaName string) *ChatThreadParticipantsTable {
	return newChatThreadParticipantsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ChatThreadParticipantsTable with assigned table prefix
func (a ChatThreadParticipantsTable) WithPrefix(prefix string) *ChatThreadParticipantsTable {
	return newChatThreadParticipantsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ChatThreadParticipantsTable with assigned table suffix
func (a ChatThreadParticipantsTable) WithSuffix(suffix string) *ChatThreadParticipantsTable {
	return newChatThreadParticipantsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newChatThreadParticipantsTable(schemaName, tableName, alias string) *ChatThreadParticipantsTable {
	return &ChatThreadParticipantsTable{
		chatThreadParticipantsTable: newChatThreadParticipantsTableImpl(schemaName, tableName, alias),
		NEW:                         newChatThreadParticipantsTableImpl("", "new", ""),
	}
}

func newChatThreadParticipantsTableImpl(schemaName, tableName, alias string) chatThreadParticipantsTable {
	var (
		ChatThreadIDColumn      = mysql.StringColumn("chat_thread_id")
		UserIDColumn            = mysql.StringColumn("user_id")
		ArchivedAtColumn        = mysql.TimestampColumn("archived_at")
		MutedAtColumn           = mysql.TimestampColumn("muted_at")
		LastReadMessageIDColumn = mysql.StringColumn("last_read_message_id")
		LastReadAtColumn        = mysql.TimestampColumn("last_read_at")
		JoinedAtColumn          = mysql.TimestampColumn("joined_at")
		LeftAtColumn            = mysql.TimestampColumn("left_at")
		allColumns              = mysql.ColumnList{ChatThreadIDColumn, UserIDColumn, ArchivedAtColumn, MutedAtColumn, LastReadMessageIDColumn, LastReadAtColumn, JoinedAtColumn, LeftAtColumn}
		mutableColumns          = mysql.ColumnList{ArchivedAtColumn, MutedAtColumn, LastReadMessageIDColumn, LastReadAtColumn, JoinedAtColumn, LeftAtColumn}
		defaultColumns          = mysql.ColumnList{JoinedAtColumn}
	)

	return chatThreadParticipantsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ChatThreadID:      ChatThreadIDColumn,
		UserID:            UserIDColumn,
		ArchivedAt:        ArchivedAtColumn,
		MutedAt:           MutedAtColumn,
		LastReadMessageID: LastReadMessageIDColumn,
		LastReadAt:        LastReadAtColumn,
		JoinedAt:          JoinedAtColumn,
		LeftAt:            LeftAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
