//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ChatMessages = newChatMessagesTable("db_crocs", "chat_messages", "")

type chatMessagesTable struct {
	mysql.Table

	// Columns
	ChatMessageID mysql.ColumnString
	ChatThreadID  mysql.ColumnString
	SenderUserID  mysql.ColumnString
	MessageType   mysql.ColumnString
	Body          mysql.ColumnString
	CreatedAt     mysql.ColumnTimestamp
	UpdatedAt     mysql.ColumnTimestamp
	DeletedAt     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ChatMessagesTable struct {
	chatMessagesTable

	NEW chatMessagesTable
}

// AS creates new ChatMessagesTable with assigned alias
func (a ChatMessagesTable) AS(alias string) *ChatMessagesTable {
	return newChatMessagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ChatMessagesTable with assigned schema name
func (a ChatMessagesTable) FromSchema(schemaName string) *ChatMessagesTable {
	return newChatMessagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ChatMessagesTable with assigned table prefix
func (a ChatMessagesTable) WithPrefix(prefix string) *ChatMessagesTable {
	return newChatMessagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ChatMessagesTable with assigned table suffix
func (a ChatMessagesTable) WithSuffix(suffix string) *ChatMessagesTable {
	return newChatMessagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newChatMessagesTable(schemaName, tableName, alias string) *ChatMessagesTable {
	return &ChatMessagesTable{
		chatMessagesTable: newChatMessagesTableImpl(schemaName, tableName, alias),
		NEW:               newChatMessagesTableImpl("", "new", ""),
	}
}

func newChatMessagesTableImpl(schemaName, tableName, alias string) chatMessagesTable {
	var (
		ChatMessageIDColumn = mysql.StringColumn("chat_message_id")
		ChatThreadIDColumn  = mysql.StringColumn("chat_thread_id")
		SenderUserIDColumn  = mysql.StringColumn("sender_user_id")
		MessageTypeColumn   = mysql.StringColumn("message_type")
		BodyColumn          = mysql.StringColumn("body")
		CreatedAtColumn     = mysql.TimestampColumn("created_at")
		UpdatedAtColumn     = mysql.TimestampColumn("updated_at")
		DeletedAtColumn     = mysql.TimestampColumn("deleted_at")
		allColumns          = mysql.ColumnList{ChatMessageIDColumn, ChatThreadIDColumn, SenderUserIDColumn, MessageTypeColumn, BodyColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns      = mysql.ColumnList{ChatThreadIDColumn, SenderUserIDColumn, MessageTypeColumn, BodyColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns      = mysql.ColumnList{MessageTypeColumn, CreatedAtColumn}
	)

	return chatMessagesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ChatMessageID: ChatMessageIDColumn,
		ChatThreadID:  ChatThreadIDColumn,
		SenderUserID:  SenderUserIDColumn,
		MessageType:   MessageTypeColumn,
		Body:          BodyColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,
		DeletedAt:     DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
