//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ChatMessageAttachments = newChatMessageAttachmentsTable("db_crocs", "chat_message_attachments", "")

type chatMessageAttachmentsTable struct {
	mysql.Table

	// Columns
	ChatMessageAttachmentID mysql.ColumnString
	ChatMessageID           mysql.ColumnString
	FileName                mysql.ColumnString
	FileType                mysql.ColumnString
	FileSize                mysql.ColumnInteger
	R2Bucket                mysql.ColumnString
	R2ObjectKey             mysql.ColumnString
	PublicURL               mysql.ColumnString
	CreatedAt               mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ChatMessageAttachmentsTable struct {
	chatMessageAttachmentsTable

	NEW chatMessageAttachmentsTable
}

// AS creates new ChatMessageAttachmentsTable with assigned alias
func (a ChatMessageAttachmentsTable) AS(alias string) *ChatMessageAttachmentsTable {
	return newChatMessageAttachmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ChatMessageAttachmentsTable with assigned schema name
func (a ChatMessageAttachmentsTable) FromSchema(schemaName string) *ChatMessageAttachmentsTable {
	return newChatMessageAttachmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ChatMessageAttachmentsTable with assigned table prefix
func (a ChatMessageAttachmentsTable) WithPrefix(prefix string) *ChatMessageAttachmentsTable {
	return newChatMessageAttachmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ChatMessageAttachmentsTable with assigned table suffix
func (a ChatMessageAttachmentsTable) WithSuffix(suffix string) *ChatMessageAttachmentsTable {
	return newChatMessageAttachmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newChatMessageAttachmentsTable(schemaName, tableName, alias string) *ChatMessageAttachmentsTable {
	return &ChatMessageAttachmentsTable{
		chatMessageAttachmentsTable: newChatMessageAttachmentsTableImpl(schemaName, tableName, alias),
		NEW:                         newChatMessageAttachmentsTableImpl("", "new", ""),
	}
}

func newChatMessageAttachmentsTableImpl(schemaName, tableName, alias string) chatMessageAttachmentsTable {
	var (
		ChatMessageAttachmentIDColumn = mysql.StringColumn("chat_message_attachment_id")
		ChatMessageIDColumn           = mysql.StringColumn("chat_message_id")
		FileNameColumn                = mysql.StringColumn("file_name")
		FileTypeColumn                = mysql.StringColumn("file_type")
		FileSizeColumn                = mysql.IntegerColumn("file_size")
		R2BucketColumn                = mysql.StringColumn("r2_bucket")
		R2ObjectKeyColumn             = mysql.StringColumn("r2_object_key")
		PublicURLColumn               = mysql.StringColumn("public_url")
		CreatedAtColumn               = mysql.TimestampColumn("created_at")
		allColumns                    = mysql.ColumnList{ChatMessageAttachmentIDColumn, ChatMessageIDColumn, FileNameColumn, FileTypeColumn, FileSizeColumn, R2BucketColumn, R2ObjectKeyColumn, PublicURLColumn, CreatedAtColumn}
		mutableColumns                = mysql.ColumnList{ChatMessageIDColumn, FileNameColumn, FileTypeColumn, FileSizeColumn, R2BucketColumn, R2ObjectKeyColumn, PublicURLColumn, CreatedAtColumn}
		defaultColumns                = mysql.ColumnList{CreatedAtColumn}
	)

	return chatMessageAttachmentsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ChatMessageAttachmentID: ChatMessageAttachmentIDColumn,
		ChatMessageID:           ChatMessageIDColumn,
		FileName:                FileNameColumn,
		FileType:                FileTypeColumn,
		FileSize:                FileSizeColumn,
		R2Bucket:                R2BucketColumn,
		R2ObjectKey:             R2ObjectKeyColumn,
		PublicURL:               PublicURLColumn,
		CreatedAt:               CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
