//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ChatThreads = newChatThreadsTable("db_crocs", "chat_threads", "")

type chatThreadsTable struct {
	mysql.Table

	// Columns
	ChatThreadID  mysql.ColumnString
	Type          mysql.ColumnString
	Title         mysql.ColumnString
	LastMessageID mysql.ColumnString
	LastMessageAt mysql.ColumnTimestamp
	CreatedAt     mysql.ColumnTimestamp
	UpdatedAt     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ChatThreadsTable struct {
	chatThreadsTable

	NEW chatThreadsTable
}

// AS creates new ChatThreadsTable with assigned alias
func (a ChatThreadsTable) AS(alias string) *ChatThreadsTable {
	return newChatThreadsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ChatThreadsTable with assigned schema name
func (a ChatThreadsTable) FromSchema(schemaName string) *ChatThreadsTable {
	return newChatThreadsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ChatThreadsTable with assigned table prefix
func (a ChatThreadsTable) WithPrefix(prefix string) *ChatThreadsTable {
	return newChatThreadsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ChatThreadsTable with assigned table suffix
func (a ChatThreadsTable) WithSuffix(suffix string) *ChatThreadsTable {
	return newChatThreadsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newChatThreadsTable(schemaName, tableName, alias string) *ChatThreadsTable {
	return &ChatThreadsTable{
		chatThreadsTable: newChatThreadsTableImpl(schemaName, tableName, alias),
		NEW:              newChatThreadsTableImpl("", "new", ""),
	}
}

func newChatThreadsTableImpl(schemaName, tableName, alias string) chatThreadsTable {
	var (
		ChatThreadIDColumn  = mysql.StringColumn("chat_thread_id")
		TypeColumn          = mysql.StringColumn("type")
		TitleColumn         = mysql.StringColumn("title")
		LastMessageIDColumn = mysql.StringColumn("last_message_id")
		LastMessageAtColumn = mysql.TimestampColumn("last_message_at")
		CreatedAtColumn     = mysql.TimestampColumn("created_at")
		UpdatedAtColumn     = mysql.TimestampColumn("updated_at")
		allColumns          = mysql.ColumnList{ChatThreadIDColumn, TypeColumn, TitleColumn, LastMessageIDColumn, LastMessageAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = mysql.ColumnList{TypeColumn, TitleColumn, LastMessageIDColumn, LastMessageAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = mysql.ColumnList{TypeColumn, CreatedAtColumn}
	)

	return chatThreadsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ChatThreadID:  ChatThreadIDColumn,
		Type:          TypeColumn,
		Title:         TitleColumn,
		LastMessageID: LastMessageIDColumn,
		LastMessageAt: LastMessageAtColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
