//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Medias = newMediasTable("db_crocs", "medias", "")

type mediasTable struct {
	mysql.Table

	// Columns
	MediaID     mysql.ColumnString
	MediaPostID mysql.ColumnString
	ObjectKey   mysql.ColumnString
	Type        mysql.ColumnString
	CreatedTime mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type MediasTable struct {
	mediasTable

	NEW mediasTable
}

// AS creates new MediasTable with assigned alias
func (a MediasTable) AS(alias string) *MediasTable {
	return newMediasTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MediasTable with assigned schema name
func (a MediasTable) FromSchema(schemaName string) *MediasTable {
	return newMediasTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MediasTable with assigned table prefix
func (a MediasTable) WithPrefix(prefix string) *MediasTable {
	return newMediasTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MediasTable with assigned table suffix
func (a MediasTable) WithSuffix(suffix string) *MediasTable {
	return newMediasTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMediasTable(schemaName, tableName, alias string) *MediasTable {
	return &MediasTable{
		mediasTable: newMediasTableImpl(schemaName, tableName, alias),
		NEW:         newMediasTableImpl("", "new", ""),
	}
}

func newMediasTableImpl(schemaName, tableName, alias string) mediasTable {
	var (
		MediaIDColumn     = mysql.StringColumn("media_id")
		MediaPostIDColumn = mysql.StringColumn("media_post_id")
		ObjectKeyColumn   = mysql.StringColumn("object_key")
		TypeColumn        = mysql.StringColumn("type")
		CreatedTimeColumn = mysql.TimestampColumn("created_time")
		allColumns        = mysql.ColumnList{MediaIDColumn, MediaPostIDColumn, ObjectKeyColumn, TypeColumn, CreatedTimeColumn}
		mutableColumns    = mysql.ColumnList{ObjectKeyColumn, TypeColumn, CreatedTimeColumn}
		defaultColumns    = mysql.ColumnList{CreatedTimeColumn}
	)

	return mediasTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		MediaID:     MediaIDColumn,
		MediaPostID: MediaPostIDColumn,
		ObjectKey:   ObjectKeyColumn,
		Type:        TypeColumn,
		CreatedTime: CreatedTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
