//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var PostReactions = newPostReactionsTable("db_crocs", "post_reactions", "")

type postReactionsTable struct {
	mysql.Table

	// Columns
	PostReactionID mysql.ColumnString
	PostID         mysql.ColumnString
	UserID         mysql.ColumnString
	ReactionType   mysql.ColumnString
	CreatedTime    mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type PostReactionsTable struct {
	postReactionsTable

	NEW postReactionsTable
}

// AS creates new PostReactionsTable with assigned alias
func (a PostReactionsTable) AS(alias string) *PostReactionsTable {
	return newPostReactionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PostReactionsTable with assigned schema name
func (a PostReactionsTable) FromSchema(schemaName string) *PostReactionsTable {
	return newPostReactionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PostReactionsTable with assigned table prefix
func (a PostReactionsTable) WithPrefix(prefix string) *PostReactionsTable {
	return newPostReactionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PostReactionsTable with assigned table suffix
func (a PostReactionsTable) WithSuffix(suffix string) *PostReactionsTable {
	return newPostReactionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPostReactionsTable(schemaName, tableName, alias string) *PostReactionsTable {
	return &PostReactionsTable{
		postReactionsTable: newPostReactionsTableImpl(schemaName, tableName, alias),
		NEW:                newPostReactionsTableImpl("", "new", ""),
	}
}

func newPostReactionsTableImpl(schemaName, tableName, alias string) postReactionsTable {
	var (
		PostReactionIDColumn = mysql.StringColumn("post_reaction_id")
		PostIDColumn         = mysql.StringColumn("post_id")
		UserIDColumn         = mysql.StringColumn("user_id")
		ReactionTypeColumn   = mysql.StringColumn("reaction_type")
		CreatedTimeColumn    = mysql.TimestampColumn("created_time")
		allColumns           = mysql.ColumnList{PostReactionIDColumn, PostIDColumn, UserIDColumn, ReactionTypeColumn, CreatedTimeColumn}
		mutableColumns       = mysql.ColumnList{PostIDColumn, UserIDColumn, ReactionTypeColumn, CreatedTimeColumn}
		defaultColumns       = mysql.ColumnList{CreatedTimeColumn}
	)

	return postReactionsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PostReactionID: PostReactionIDColumn,
		PostID:         PostIDColumn,
		UserID:         UserIDColumn,
		ReactionType:   ReactionTypeColumn,
		CreatedTime:    CreatedTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
