//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var PostComments = newPostCommentsTable("db_crocs", "post_comments", "")

type postCommentsTable struct {
	mysql.Table

	// Columns
	CommentID       mysql.ColumnString
	PostID          mysql.ColumnString
	UserID          mysql.ColumnString
	ParentCommentID mysql.ColumnString
	Content         mysql.ColumnString
	CreatedTime     mysql.ColumnTimestamp
	UpdatedTime     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type PostCommentsTable struct {
	postCommentsTable

	NEW postCommentsTable
}

// AS creates new PostCommentsTable with assigned alias
func (a PostCommentsTable) AS(alias string) *PostCommentsTable {
	return newPostCommentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PostCommentsTable with assigned schema name
func (a PostCommentsTable) FromSchema(schemaName string) *PostCommentsTable {
	return newPostCommentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PostCommentsTable with assigned table prefix
func (a PostCommentsTable) WithPrefix(prefix string) *PostCommentsTable {
	return newPostCommentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PostCommentsTable with assigned table suffix
func (a PostCommentsTable) WithSuffix(suffix string) *PostCommentsTable {
	return newPostCommentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPostCommentsTable(schemaName, tableName, alias string) *PostCommentsTable {
	return &PostCommentsTable{
		postCommentsTable: newPostCommentsTableImpl(schemaName, tableName, alias),
		NEW:               newPostCommentsTableImpl("", "new", ""),
	}
}

func newPostCommentsTableImpl(schemaName, tableName, alias string) postCommentsTable {
	var (
		CommentIDColumn       = mysql.StringColumn("comment_id")
		PostIDColumn          = mysql.StringColumn("post_id")
		UserIDColumn          = mysql.StringColumn("user_id")
		ParentCommentIDColumn = mysql.StringColumn("parent_comment_id")
		ContentColumn         = mysql.StringColumn("content")
		CreatedTimeColumn     = mysql.TimestampColumn("created_time")
		UpdatedTimeColumn     = mysql.TimestampColumn("updated_time")
		allColumns            = mysql.ColumnList{CommentIDColumn, PostIDColumn, UserIDColumn, ParentCommentIDColumn, ContentColumn, CreatedTimeColumn, UpdatedTimeColumn}
		mutableColumns        = mysql.ColumnList{PostIDColumn, UserIDColumn, ParentCommentIDColumn, ContentColumn, CreatedTimeColumn, UpdatedTimeColumn}
		defaultColumns        = mysql.ColumnList{CreatedTimeColumn}
	)

	return postCommentsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		CommentID:       CommentIDColumn,
		PostID:          PostIDColumn,
		UserID:          UserIDColumn,
		ParentCommentID: ParentCommentIDColumn,
		Content:         ContentColumn,
		CreatedTime:     CreatedTimeColumn,
		UpdatedTime:     UpdatedTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
