//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ProjectLikes = newProjectLikesTable("db_crocs", "project_likes", "")

type projectLikesTable struct {
	mysql.Table

	// Columns
	ProjectID     mysql.ColumnString
	ProjectUserID mysql.ColumnString
	CreatedTime   mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ProjectLikesTable struct {
	projectLikesTable

	NEW projectLikesTable
}

// AS creates new ProjectLikesTable with assigned alias
func (a ProjectLikesTable) AS(alias string) *ProjectLikesTable {
	return newProjectLikesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProjectLikesTable with assigned schema name
func (a ProjectLikesTable) FromSchema(schemaName string) *ProjectLikesTable {
	return newProjectLikesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProjectLikesTable with assigned table prefix
func (a ProjectLikesTable) WithPrefix(prefix string) *ProjectLikesTable {
	return newProjectLikesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProjectLikesTable with assigned table suffix
func (a ProjectLikesTable) WithSuffix(suffix string) *ProjectLikesTable {
	return newProjectLikesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProjectLikesTable(schemaName, tableName, alias string) *ProjectLikesTable {
	return &ProjectLikesTable{
		projectLikesTable: newProjectLikesTableImpl(schemaName, tableName, alias),
		NEW:               newProjectLikesTableImpl("", "new", ""),
	}
}

func newProjectLikesTableImpl(schemaName, tableName, alias string) projectLikesTable {
	var (
		ProjectIDColumn     = mysql.StringColumn("project_id")
		ProjectUserIDColumn = mysql.StringColumn("project_user_id")
		CreatedTimeColumn   = mysql.TimestampColumn("created_time")
		allColumns          = mysql.ColumnList{ProjectIDColumn, ProjectUserIDColumn, CreatedTimeColumn}
		mutableColumns      = mysql.ColumnList{CreatedTimeColumn}
		defaultColumns      = mysql.ColumnList{CreatedTimeColumn}
	)

	return projectLikesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ProjectID:     ProjectIDColumn,
		ProjectUserID: ProjectUserIDColumn,
		CreatedTime:   CreatedTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
