//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Reactions = newReactionsTable("db_crocs", "reactions", "")

type reactionsTable struct {
	mysql.Table

	// Columns
	ReactionID        mysql.ColumnString
	ReactionProjectID mysql.ColumnString
	Type              mysql.ColumnString
	CreatedTime       mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ReactionsTable struct {
	reactionsTable

	NEW reactionsTable
}

// AS creates new ReactionsTable with assigned alias
func (a ReactionsTable) AS(alias string) *ReactionsTable {
	return newReactionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReactionsTable with assigned schema name
func (a ReactionsTable) FromSchema(schemaName string) *ReactionsTable {
	return newReactionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReactionsTable with assigned table prefix
func (a ReactionsTable) WithPrefix(prefix string) *ReactionsTable {
	return newReactionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReactionsTable with assigned table suffix
func (a ReactionsTable) WithSuffix(suffix string) *ReactionsTable {
	return newReactionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReactionsTable(schemaName, tableName, alias string) *ReactionsTable {
	return &ReactionsTable{
		reactionsTable: newReactionsTableImpl(schemaName, tableName, alias),
		NEW:            newReactionsTableImpl("", "new", ""),
	}
}

func newReactionsTableImpl(schemaName, tableName, alias string) reactionsTable {
	var (
		ReactionIDColumn        = mysql.StringColumn("reaction_id")
		ReactionProjectIDColumn = mysql.StringColumn("reaction_project_id")
		TypeColumn              = mysql.StringColumn("type")
		CreatedTimeColumn       = mysql.TimestampColumn("created_time")
		allColumns              = mysql.ColumnList{ReactionIDColumn, ReactionProjectIDColumn, TypeColumn, CreatedTimeColumn}
		mutableColumns          = mysql.ColumnList{TypeColumn, CreatedTimeColumn}
		defaultColumns          = mysql.ColumnList{CreatedTimeColumn}
	)

	return reactionsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ReactionID:        ReactionIDColumn,
		ReactionProjectID: ReactionProjectIDColumn,
		Type:              TypeColumn,
		CreatedTime:       CreatedTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
