//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	ChatMessageAttachments = ChatMessageAttachments.FromSchema(schema)
	ChatMessages = ChatMessages.FromSchema(schema)
	ChatThreadParticipants = ChatThreadParticipants.FromSchema(schema)
	ChatThreads = ChatThreads.FromSchema(schema)
	Medias = Medias.FromSchema(schema)
	PostComments = PostComments.FromSchema(schema)
	PostReactions = PostReactions.FromSchema(schema)
	Posts = Posts.FromSchema(schema)
	ProjectLikes = ProjectLikes.FromSchema(schema)
	Projects = Projects.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
