//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var ChatMessagesMessageType = &struct {
	Text       mysql.StringExpression
	Image      mysql.StringExpression
	Attachment mysql.StringExpression
}{
	Text:       mysql.NewEnumValue("text"),
	Image:      mysql.NewEnumValue("image"),
	Attachment: mysql.NewEnumValue("attachment"),
}
