//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var ChatThreadsType = &struct {
	Direct mysql.StringExpression
	Group  mysql.StringExpression
}{
	Direct: mysql.NewEnumValue("direct"),
	Group:  mysql.NewEnumValue("group"),
}
