//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type MediasType string

const (
	MediasType_Image MediasType = "Image"
	MediasType_Video MediasType = "Video"
)

var MediasTypeAllValues = []MediasType{
	MediasType_Image,
	MediasType_Video,
}

func (e *MediasType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Image":
		*e = MediasType_Image
	case "Video":
		*e = MediasType_Video
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for MediasType enum")
	}

	return nil
}

func (e MediasType) String() string {
	return string(e)
}
