//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PostsVisibility string

const (
	PostsVisibility_Public  PostsVisibility = "Public"
	PostsVisibility_Private PostsVisibility = "Private"
)

var PostsVisibilityAllValues = []PostsVisibility{
	PostsVisibility_Public,
	PostsVisibility_Private,
}

func (e *PostsVisibility) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Public":
		*e = PostsVisibility_Public
	case "Private":
		*e = PostsVisibility_Private
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PostsVisibility enum")
	}

	return nil
}

func (e PostsVisibility) String() string {
	return string(e)
}
