// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: media.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaService_ShowMedias_FullMethodName  = "/media.MediaService/ShowMedias"
	MediaService_ShowMedia_FullMethodName   = "/media.MediaService/ShowMedia"
	MediaService_CreateMedia_FullMethodName = "/media.MediaService/CreateMedia"
	MediaService_UpdateMedia_FullMethodName = "/media.MediaService/UpdateMedia"
	MediaService_RemoveMedia_FullMethodName = "/media.MediaService/RemoveMedia"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	ShowMedias(ctx context.Context, in *ShowMediasIn, opts ...grpc.CallOption) (*ShowMediasOut, error)
	ShowMedia(ctx context.Context, in *ShowMediaIn, opts ...grpc.CallOption) (*ShowMediaOut, error)
	CreateMedia(ctx context.Context, in *CreateMediaIn, opts ...grpc.CallOption) (*CreateMediaOut, error)
	UpdateMedia(ctx context.Context, in *UpdateMediaIn, opts ...grpc.CallOption) (*UpdateMediaOut, error)
	RemoveMedia(ctx context.Context, in *RemoveMediaIn, opts ...grpc.CallOption) (*RemoveMediaOut, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) ShowMedias(ctx context.Context, in *ShowMediasIn, opts ...grpc.CallOption) (*ShowMediasOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowMediasOut)
	err := c.cc.Invoke(ctx, MediaService_ShowMedias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) ShowMedia(ctx context.Context, in *ShowMediaIn, opts ...grpc.CallOption) (*ShowMediaOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowMediaOut)
	err := c.cc.Invoke(ctx, MediaService_ShowMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) CreateMedia(ctx context.Context, in *CreateMediaIn, opts ...grpc.CallOption) (*CreateMediaOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMediaOut)
	err := c.cc.Invoke(ctx, MediaService_CreateMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UpdateMedia(ctx context.Context, in *UpdateMediaIn, opts ...grpc.CallOption) (*UpdateMediaOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMediaOut)
	err := c.cc.Invoke(ctx, MediaService_UpdateMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) RemoveMedia(ctx context.Context, in *RemoveMediaIn, opts ...grpc.CallOption) (*RemoveMediaOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMediaOut)
	err := c.cc.Invoke(ctx, MediaService_RemoveMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility.
type MediaServiceServer interface {
	ShowMedias(context.Context, *ShowMediasIn) (*ShowMediasOut, error)
	ShowMedia(context.Context, *ShowMediaIn) (*ShowMediaOut, error)
	CreateMedia(context.Context, *CreateMediaIn) (*CreateMediaOut, error)
	UpdateMedia(context.Context, *UpdateMediaIn) (*UpdateMediaOut, error)
	RemoveMedia(context.Context, *RemoveMediaIn) (*RemoveMediaOut, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaServiceServer struct{}

func (UnimplementedMediaServiceServer) ShowMedias(context.Context, *ShowMediasIn) (*ShowMediasOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowMedias not implemented")
}
func (UnimplementedMediaServiceServer) ShowMedia(context.Context, *ShowMediaIn) (*ShowMediaOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowMedia not implemented")
}
func (UnimplementedMediaServiceServer) CreateMedia(context.Context, *CreateMediaIn) (*CreateMediaOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMedia not implemented")
}
func (UnimplementedMediaServiceServer) UpdateMedia(context.Context, *UpdateMediaIn) (*UpdateMediaOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMedia not implemented")
}
func (UnimplementedMediaServiceServer) RemoveMedia(context.Context, *RemoveMediaIn) (*RemoveMediaOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMedia not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}
func (UnimplementedMediaServiceServer) testEmbeddedByValue()                      {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	// If the following call pancis, it indicates UnimplementedMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_ShowMedias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowMediasIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).ShowMedias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_ShowMedias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).ShowMedias(ctx, req.(*ShowMediasIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_ShowMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowMediaIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).ShowMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_ShowMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).ShowMedia(ctx, req.(*ShowMediaIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_CreateMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMediaIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).CreateMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_CreateMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).CreateMedia(ctx, req.(*CreateMediaIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UpdateMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMediaIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).UpdateMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_UpdateMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).UpdateMedia(ctx, req.(*UpdateMediaIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_RemoveMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMediaIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).RemoveMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_RemoveMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).RemoveMedia(ctx, req.(*RemoveMediaIn))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowMedias",
			Handler:    _MediaService_ShowMedias_Handler,
		},
		{
			MethodName: "ShowMedia",
			Handler:    _MediaService_ShowMedia_Handler,
		},
		{
			MethodName: "CreateMedia",
			Handler:    _MediaService_CreateMedia_Handler,
		},
		{
			MethodName: "UpdateMedia",
			Handler:    _MediaService_UpdateMedia_Handler,
		},
		{
			MethodName: "RemoveMedia",
			Handler:    _MediaService_RemoveMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media.proto",
}
