// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: media.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_IMAGE       MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO       MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_IMAGE",
		2: "MEDIA_TYPE_VIDEO",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_IMAGE":       1,
		"MEDIA_TYPE_VIDEO":       2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

type ShowMediasIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowMediasIn) Reset() {
	*x = ShowMediasIn{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowMediasIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowMediasIn) ProtoMessage() {}

func (x *ShowMediasIn) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowMediasIn.ProtoReflect.Descriptor instead.
func (*ShowMediasIn) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

type ShowMediasOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ViewMedia           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowMediasOut) Reset() {
	*x = ShowMediasOut{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowMediasOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowMediasOut) ProtoMessage() {}

func (x *ShowMediasOut) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowMediasOut.ProtoReflect.Descriptor instead.
func (*ShowMediasOut) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *ShowMediasOut) GetItems() []*ViewMedia {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShowMediasOut) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ShowMediaIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowMediaIn) Reset() {
	*x = ShowMediaIn{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowMediaIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowMediaIn) ProtoMessage() {}

func (x *ShowMediaIn) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowMediaIn.ProtoReflect.Descriptor instead.
func (*ShowMediaIn) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *ShowMediaIn) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type ShowMediaOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ViewMedia             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowMediaOut) Reset() {
	*x = ShowMediaOut{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowMediaOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowMediaOut) ProtoMessage() {}

func (x *ShowMediaOut) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowMediaOut.ProtoReflect.Descriptor instead.
func (*ShowMediaOut) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *ShowMediaOut) GetItem() *ViewMedia {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateMediaIn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MediaProjectId string                 `protobuf:"bytes,1,opt,name=media_project_id,json=mediaProjectId,proto3" json:"media_project_id,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Type           MediaType              `protobuf:"varint,3,opt,name=type,proto3,enum=media.MediaType" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMediaIn) Reset() {
	*x = CreateMediaIn{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaIn) ProtoMessage() {}

func (x *CreateMediaIn) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaIn.ProtoReflect.Descriptor instead.
func (*CreateMediaIn) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMediaIn) GetMediaProjectId() string {
	if x != nil {
		return x.MediaProjectId
	}
	return ""
}

func (x *CreateMediaIn) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateMediaIn) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

type CreateMediaOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaOut) Reset() {
	*x = CreateMediaOut{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaOut) ProtoMessage() {}

func (x *CreateMediaOut) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaOut.ProtoReflect.Descriptor instead.
func (*CreateMediaOut) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

type UpdateMediaIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaIn) Reset() {
	*x = UpdateMediaIn{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaIn) ProtoMessage() {}

func (x *UpdateMediaIn) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaIn.ProtoReflect.Descriptor instead.
func (*UpdateMediaIn) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMediaIn) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *UpdateMediaIn) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateMediaOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaOut) Reset() {
	*x = UpdateMediaOut{}
	mi := &file_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaOut) ProtoMessage() {}

func (x *UpdateMediaOut) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaOut.ProtoReflect.Descriptor instead.
func (*UpdateMediaOut) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{7}
}

type RemoveMediaIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMediaIn) Reset() {
	*x = RemoveMediaIn{}
	mi := &file_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMediaIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMediaIn) ProtoMessage() {}

func (x *RemoveMediaIn) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMediaIn.ProtoReflect.Descriptor instead.
func (*RemoveMediaIn) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveMediaIn) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type RemoveMediaOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMediaOut) Reset() {
	*x = RemoveMediaOut{}
	mi := &file_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMediaOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMediaOut) ProtoMessage() {}

func (x *RemoveMediaOut) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMediaOut.ProtoReflect.Descriptor instead.
func (*RemoveMediaOut) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{9}
}

type ViewMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMedia) Reset() {
	*x = ViewMedia{}
	mi := &file_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMedia) ProtoMessage() {}

func (x *ViewMedia) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMedia.ProtoReflect.Descriptor instead.
func (*ViewMedia) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{10}
}

func (x *ViewMedia) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type Media struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MediaId        string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	MediaProjectId string                 `protobuf:"bytes,2,opt,name=media_project_id,json=mediaProjectId,proto3" json:"media_project_id,omitempty"`
	Url            string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CreatedTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{11}
}

func (x *Media) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Media) GetMediaProjectId() string {
	if x != nil {
		return x.MediaProjectId
	}
	return ""
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x05media\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fShowMediasIn\"M\n" +
	"\rShowMediasOut\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.media.ViewMediaR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"(\n" +
	"\vShowMediaIn\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"4\n" +
	"\fShowMediaOut\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.media.ViewMediaR\x04item\"q\n" +
	"\rCreateMediaIn\x12(\n" +
	"\x10media_project_id\x18\x01 \x01(\tR\x0emediaProjectId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.media.MediaTypeR\x04type\"\x10\n" +
	"\x0eCreateMediaOut\"<\n" +
	"\rUpdateMediaIn\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x10\n" +
	"\x0eUpdateMediaOut\"*\n" +
	"\rRemoveMediaIn\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\x10\n" +
	"\x0eRemoveMediaOut\"/\n" +
	"\tViewMedia\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"\xb1\x01\n" +
	"\x05Media\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12(\n" +
	"\x10media_project_id\x18\x02 \x01(\tR\x0emediaProjectId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12=\n" +
	"\fcreated_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime*S\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x022\xb1\x02\n" +
	"\fMediaService\x127\n" +
	"\n" +
	"ShowMedias\x12\x13.media.ShowMediasIn\x1a\x14.media.ShowMediasOut\x124\n" +
	"\tShowMedia\x12\x12.media.ShowMediaIn\x1a\x13.media.ShowMediaOut\x12:\n" +
	"\vCreateMedia\x12\x14.media.CreateMediaIn\x1a\x15.media.CreateMediaOut\x12:\n" +
	"\vUpdateMedia\x12\x14.media.UpdateMediaIn\x1a\x15.media.UpdateMediaOut\x12:\n" +
	"\vRemoveMedia\x12\x14.media.RemoveMediaIn\x1a\x15.media.RemoveMediaOutBBZ@github.com/Jmaglinte-Projects/crocsbook-go-app/infra/grpc/protosb\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_media_proto_goTypes = []any{
	(MediaType)(0),                // 0: media.MediaType
	(*ShowMediasIn)(nil),          // 1: media.ShowMediasIn
	(*ShowMediasOut)(nil),         // 2: media.ShowMediasOut
	(*ShowMediaIn)(nil),           // 3: media.ShowMediaIn
	(*ShowMediaOut)(nil),          // 4: media.ShowMediaOut
	(*CreateMediaIn)(nil),         // 5: media.CreateMediaIn
	(*CreateMediaOut)(nil),        // 6: media.CreateMediaOut
	(*UpdateMediaIn)(nil),         // 7: media.UpdateMediaIn
	(*UpdateMediaOut)(nil),        // 8: media.UpdateMediaOut
	(*RemoveMediaIn)(nil),         // 9: media.RemoveMediaIn
	(*RemoveMediaOut)(nil),        // 10: media.RemoveMediaOut
	(*ViewMedia)(nil),             // 11: media.ViewMedia
	(*Media)(nil),                 // 12: media.Media
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_media_proto_depIdxs = []int32{
	11, // 0: media.ShowMediasOut.items:type_name -> media.ViewMedia
	11, // 1: media.ShowMediaOut.item:type_name -> media.ViewMedia
	0,  // 2: media.CreateMediaIn.type:type_name -> media.MediaType
	12, // 3: media.ViewMedia.media:type_name -> media.Media
	13, // 4: media.Media.created_time:type_name -> google.protobuf.Timestamp
	1,  // 5: media.MediaService.ShowMedias:input_type -> media.ShowMediasIn
	3,  // 6: media.MediaService.ShowMedia:input_type -> media.ShowMediaIn
	5,  // 7: media.MediaService.CreateMedia:input_type -> media.CreateMediaIn
	7,  // 8: media.MediaService.UpdateMedia:input_type -> media.UpdateMediaIn
	9,  // 9: media.MediaService.RemoveMedia:input_type -> media.RemoveMediaIn
	2,  // 10: media.MediaService.ShowMedias:output_type -> media.ShowMediasOut
	4,  // 11: media.MediaService.ShowMedia:output_type -> media.ShowMediaOut
	6,  // 12: media.MediaService.CreateMedia:output_type -> media.CreateMediaOut
	8,  // 13: media.MediaService.UpdateMedia:output_type -> media.UpdateMediaOut
	10, // 14: media.MediaService.RemoveMedia:output_type -> media.RemoveMediaOut
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		EnumInfos:         file_media_proto_enumTypes,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
