// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: post.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostVisibility int32

const (
	PostVisibility_PostVisibility_UNSPECIFIED PostVisibility = 0
	PostVisibility_PostVisibility_Public      PostVisibility = 1
	PostVisibility_PostVisibility_Private     PostVisibility = 2
)

// Enum value maps for PostVisibility.
var (
	PostVisibility_name = map[int32]string{
		0: "PostVisibility_UNSPECIFIED",
		1: "PostVisibility_Public",
		2: "PostVisibility_Private",
	}
	PostVisibility_value = map[string]int32{
		"PostVisibility_UNSPECIFIED": 0,
		"PostVisibility_Public":      1,
		"PostVisibility_Private":     2,
	}
)

func (x PostVisibility) Enum() *PostVisibility {
	p := new(PostVisibility)
	*p = x
	return p
}

func (x PostVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_post_proto_enumTypes[0].Descriptor()
}

func (PostVisibility) Type() protoreflect.EnumType {
	return &file_post_proto_enumTypes[0]
}

func (x PostVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostVisibility.Descriptor instead.
func (PostVisibility) EnumDescriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

type ShowPostsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowPostsIn) Reset() {
	*x = ShowPostsIn{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowPostsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowPostsIn) ProtoMessage() {}

func (x *ShowPostsIn) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowPostsIn.ProtoReflect.Descriptor instead.
func (*ShowPostsIn) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

type ShowPostsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ViewPost            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowPostsOut) Reset() {
	*x = ShowPostsOut{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowPostsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowPostsOut) ProtoMessage() {}

func (x *ShowPostsOut) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowPostsOut.ProtoReflect.Descriptor instead.
func (*ShowPostsOut) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *ShowPostsOut) GetItems() []*ViewPost {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShowPostsOut) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ShowPostIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowPostIn) Reset() {
	*x = ShowPostIn{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowPostIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowPostIn) ProtoMessage() {}

func (x *ShowPostIn) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowPostIn.ProtoReflect.Descriptor instead.
func (*ShowPostIn) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *ShowPostIn) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type ShowPostOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ViewPost              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowPostOut) Reset() {
	*x = ShowPostOut{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowPostOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowPostOut) ProtoMessage() {}

func (x *ShowPostOut) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowPostOut.ProtoReflect.Descriptor instead.
func (*ShowPostOut) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *ShowPostOut) GetItem() *ViewPost {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreatePostIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostProjectId string                 `protobuf:"bytes,1,opt,name=post_project_id,json=postProjectId,proto3" json:"post_project_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Visibility    PostVisibility         `protobuf:"varint,3,opt,name=visibility,proto3,enum=post.PostVisibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostIn) Reset() {
	*x = CreatePostIn{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostIn) ProtoMessage() {}

func (x *CreatePostIn) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostIn.ProtoReflect.Descriptor instead.
func (*CreatePostIn) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostIn) GetPostProjectId() string {
	if x != nil {
		return x.PostProjectId
	}
	return ""
}

func (x *CreatePostIn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostIn) GetVisibility() PostVisibility {
	if x != nil {
		return x.Visibility
	}
	return PostVisibility_PostVisibility_UNSPECIFIED
}

type CreatePostOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostOut) Reset() {
	*x = CreatePostOut{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostOut) ProtoMessage() {}

func (x *CreatePostOut) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostOut.ProtoReflect.Descriptor instead.
func (*CreatePostOut) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

type UpdatePostIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	PostProjectId string                 `protobuf:"bytes,2,opt,name=post_project_id,json=postProjectId,proto3" json:"post_project_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Visibility    PostVisibility         `protobuf:"varint,4,opt,name=visibility,proto3,enum=post.PostVisibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostIn) Reset() {
	*x = UpdatePostIn{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostIn) ProtoMessage() {}

func (x *UpdatePostIn) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostIn.ProtoReflect.Descriptor instead.
func (*UpdatePostIn) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePostIn) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdatePostIn) GetPostProjectId() string {
	if x != nil {
		return x.PostProjectId
	}
	return ""
}

func (x *UpdatePostIn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostIn) GetVisibility() PostVisibility {
	if x != nil {
		return x.Visibility
	}
	return PostVisibility_PostVisibility_UNSPECIFIED
}

type UpdatePostOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostOut) Reset() {
	*x = UpdatePostOut{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostOut) ProtoMessage() {}

func (x *UpdatePostOut) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostOut.ProtoReflect.Descriptor instead.
func (*UpdatePostOut) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

type RemovePostIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePostIn) Reset() {
	*x = RemovePostIn{}
	mi := &file_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePostIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePostIn) ProtoMessage() {}

func (x *RemovePostIn) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePostIn.ProtoReflect.Descriptor instead.
func (*RemovePostIn) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{8}
}

func (x *RemovePostIn) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type RemovePostOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePostOut) Reset() {
	*x = RemovePostOut{}
	mi := &file_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePostOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePostOut) ProtoMessage() {}

func (x *RemovePostOut) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePostOut.ProtoReflect.Descriptor instead.
func (*RemovePostOut) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{9}
}

type ViewPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewPost) Reset() {
	*x = ViewPost{}
	mi := &file_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewPost) ProtoMessage() {}

func (x *ViewPost) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewPost.ProtoReflect.Descriptor instead.
func (*ViewPost) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{10}
}

func (x *ViewPost) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	PostProjectId string                 `protobuf:"bytes,2,opt,name=post_project_id,json=postProjectId,proto3" json:"post_project_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Visibility    PostVisibility         `protobuf:"varint,4,opt,name=visibility,proto3,enum=post.PostVisibility" json:"visibility,omitempty"`
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{11}
}

func (x *Post) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Post) GetPostProjectId() string {
	if x != nil {
		return x.PostProjectId
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetVisibility() PostVisibility {
	if x != nil {
		return x.Visibility
	}
	return PostVisibility_PostVisibility_UNSPECIFIED
}

func (x *Post) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *Post) GetUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTime
	}
	return nil
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\x04post\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vShowPostsIn\"J\n" +
	"\fShowPostsOut\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.post.ViewPostR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"%\n" +
	"\n" +
	"ShowPostIn\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"1\n" +
	"\vShowPostOut\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.post.ViewPostR\x04item\"\x86\x01\n" +
	"\fCreatePostIn\x12&\n" +
	"\x0fpost_project_id\x18\x01 \x01(\tR\rpostProjectId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x124\n" +
	"\n" +
	"visibility\x18\x03 \x01(\x0e2\x14.post.PostVisibilityR\n" +
	"visibility\"\x0f\n" +
	"\rCreatePostOut\"\x9f\x01\n" +
	"\fUpdatePostIn\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12&\n" +
	"\x0fpost_project_id\x18\x02 \x01(\tR\rpostProjectId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x124\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x14.post.PostVisibilityR\n" +
	"visibility\"\x0f\n" +
	"\rUpdatePostOut\"'\n" +
	"\fRemovePostIn\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"\x0f\n" +
	"\rRemovePostOut\"*\n" +
	"\bViewPost\x12\x1e\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".post.PostR\x04post\"\x95\x02\n" +
	"\x04Post\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12&\n" +
	"\x0fpost_project_id\x18\x02 \x01(\tR\rpostProjectId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x124\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x14.post.PostVisibilityR\n" +
	"visibility\x12=\n" +
	"\fcreated_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12=\n" +
	"\fupdated_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vupdatedTime*g\n" +
	"\x0ePostVisibility\x12\x1e\n" +
	"\x1aPostVisibility_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PostVisibility_Public\x10\x01\x12\x1a\n" +
	"\x16PostVisibility_Private\x10\x022\x97\x02\n" +
	"\vPostService\x122\n" +
	"\tShowPosts\x12\x11.post.ShowPostsIn\x1a\x12.post.ShowPostsOut\x12/\n" +
	"\bShowPost\x12\x10.post.ShowPostIn\x1a\x11.post.ShowPostOut\x125\n" +
	"\n" +
	"CreatePost\x12\x12.post.CreatePostIn\x1a\x13.post.CreatePostOut\x125\n" +
	"\n" +
	"UpdatePost\x12\x12.post.UpdatePostIn\x1a\x13.post.UpdatePostOut\x125\n" +
	"\n" +
	"RemovePost\x12\x12.post.RemovePostIn\x1a\x13.post.RemovePostOutBBZ@github.com/Jmaglinte-Projects/crocsbook-go-app/infra/grpc/protosb\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_post_proto_goTypes = []any{
	(PostVisibility)(0),           // 0: post.PostVisibility
	(*ShowPostsIn)(nil),           // 1: post.ShowPostsIn
	(*ShowPostsOut)(nil),          // 2: post.ShowPostsOut
	(*ShowPostIn)(nil),            // 3: post.ShowPostIn
	(*ShowPostOut)(nil),           // 4: post.ShowPostOut
	(*CreatePostIn)(nil),          // 5: post.CreatePostIn
	(*CreatePostOut)(nil),         // 6: post.CreatePostOut
	(*UpdatePostIn)(nil),          // 7: post.UpdatePostIn
	(*UpdatePostOut)(nil),         // 8: post.UpdatePostOut
	(*RemovePostIn)(nil),          // 9: post.RemovePostIn
	(*RemovePostOut)(nil),         // 10: post.RemovePostOut
	(*ViewPost)(nil),              // 11: post.ViewPost
	(*Post)(nil),                  // 12: post.Post
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_post_proto_depIdxs = []int32{
	11, // 0: post.ShowPostsOut.items:type_name -> post.ViewPost
	11, // 1: post.ShowPostOut.item:type_name -> post.ViewPost
	0,  // 2: post.CreatePostIn.visibility:type_name -> post.PostVisibility
	0,  // 3: post.UpdatePostIn.visibility:type_name -> post.PostVisibility
	12, // 4: post.ViewPost.post:type_name -> post.Post
	0,  // 5: post.Post.visibility:type_name -> post.PostVisibility
	13, // 6: post.Post.created_time:type_name -> google.protobuf.Timestamp
	13, // 7: post.Post.updated_time:type_name -> google.protobuf.Timestamp
	1,  // 8: post.PostService.ShowPosts:input_type -> post.ShowPostsIn
	3,  // 9: post.PostService.ShowPost:input_type -> post.ShowPostIn
	5,  // 10: post.PostService.CreatePost:input_type -> post.CreatePostIn
	7,  // 11: post.PostService.UpdatePost:input_type -> post.UpdatePostIn
	9,  // 12: post.PostService.RemovePost:input_type -> post.RemovePostIn
	2,  // 13: post.PostService.ShowPosts:output_type -> post.ShowPostsOut
	4,  // 14: post.PostService.ShowPost:output_type -> post.ShowPostOut
	6,  // 15: post.PostService.CreatePost:output_type -> post.CreatePostOut
	8,  // 16: post.PostService.UpdatePost:output_type -> post.UpdatePostOut
	10, // 17: post.PostService.RemovePost:output_type -> post.RemovePostOut
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		EnumInfos:         file_post_proto_enumTypes,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
