// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: project.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowProjectsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowProjectsIn) Reset() {
	*x = ShowProjectsIn{}
	mi := &file_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowProjectsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProjectsIn) ProtoMessage() {}

func (x *ShowProjectsIn) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProjectsIn.ProtoReflect.Descriptor instead.
func (*ShowProjectsIn) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

type ShowProjectsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ViewProject         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowProjectsOut) Reset() {
	*x = ShowProjectsOut{}
	mi := &file_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowProjectsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProjectsOut) ProtoMessage() {}

func (x *ShowProjectsOut) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProjectsOut.ProtoReflect.Descriptor instead.
func (*ShowProjectsOut) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{1}
}

func (x *ShowProjectsOut) GetItems() []*ViewProject {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShowProjectsOut) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ShowProjectIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowProjectIn) Reset() {
	*x = ShowProjectIn{}
	mi := &file_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowProjectIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProjectIn) ProtoMessage() {}

func (x *ShowProjectIn) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProjectIn.ProtoReflect.Descriptor instead.
func (*ShowProjectIn) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{2}
}

func (x *ShowProjectIn) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ShowProjectOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ViewProject           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowProjectOut) Reset() {
	*x = ShowProjectOut{}
	mi := &file_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowProjectOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProjectOut) ProtoMessage() {}

func (x *ShowProjectOut) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProjectOut.ProtoReflect.Descriptor instead.
func (*ShowProjectOut) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{3}
}

func (x *ShowProjectOut) GetItem() *ViewProject {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateProjectIn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectUserId  string                 `protobuf:"bytes,1,opt,name=project_user_id,json=projectUserId,proto3" json:"project_user_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnail      string                 `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Location       string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Cost           int64                  `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	CompletionDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProjectIn) Reset() {
	*x = CreateProjectIn{}
	mi := &file_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectIn) ProtoMessage() {}

func (x *CreateProjectIn) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectIn.ProtoReflect.Descriptor instead.
func (*CreateProjectIn) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProjectIn) GetProjectUserId() string {
	if x != nil {
		return x.ProjectUserId
	}
	return ""
}

func (x *CreateProjectIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectIn) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectIn) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *CreateProjectIn) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateProjectIn) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CreateProjectIn) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateProjectIn) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

type CreateProjectOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectOut) Reset() {
	*x = CreateProjectOut{}
	mi := &file_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectOut) ProtoMessage() {}

func (x *CreateProjectOut) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectOut.ProtoReflect.Descriptor instead.
func (*CreateProjectOut) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{5}
}

type UpdateProjectIn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnail      string                 `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Location       string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Cost           int64                  `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	CompletionDate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProjectIn) Reset() {
	*x = UpdateProjectIn{}
	mi := &file_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectIn) ProtoMessage() {}

func (x *UpdateProjectIn) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectIn.ProtoReflect.Descriptor instead.
func (*UpdateProjectIn) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProjectIn) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectIn) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectIn) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *UpdateProjectIn) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateProjectIn) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *UpdateProjectIn) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateProjectIn) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

type UpdateProjectOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectOut) Reset() {
	*x = UpdateProjectOut{}
	mi := &file_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectOut) ProtoMessage() {}

func (x *UpdateProjectOut) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectOut.ProtoReflect.Descriptor instead.
func (*UpdateProjectOut) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{7}
}

type RemoveProjectIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectIn) Reset() {
	*x = RemoveProjectIn{}
	mi := &file_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectIn) ProtoMessage() {}

func (x *RemoveProjectIn) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectIn.ProtoReflect.Descriptor instead.
func (*RemoveProjectIn) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveProjectIn) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type RemoveProjectOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectOut) Reset() {
	*x = RemoveProjectOut{}
	mi := &file_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectOut) ProtoMessage() {}

func (x *RemoveProjectOut) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectOut.ProtoReflect.Descriptor instead.
func (*RemoveProjectOut) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{9}
}

type ViewProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewProject) Reset() {
	*x = ViewProject{}
	mi := &file_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewProject) ProtoMessage() {}

func (x *ViewProject) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewProject.ProtoReflect.Descriptor instead.
func (*ViewProject) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{10}
}

func (x *ViewProject) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type Project struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectUserId  string                 `protobuf:"bytes,2,opt,name=project_user_id,json=projectUserId,proto3" json:"project_user_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnail      string                 `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Location       string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Cost           int64                  `protobuf:"varint,7,opt,name=cost,proto3" json:"cost,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	CompletionDate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	CreatedTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{11}
}

func (x *Project) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Project) GetProjectUserId() string {
	if x != nil {
		return x.ProjectUserId
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Project) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Project) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Project) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Project) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *Project) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *Project) GetUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTime
	}
	return nil
}

var File_project_proto protoreflect.FileDescriptor

const file_project_proto_rawDesc = "" +
	"\n" +
	"\rproject.proto\x12\aproject\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eShowProjectsIn\"S\n" +
	"\x0fShowProjectsOut\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.project.ViewProjectR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\".\n" +
	"\rShowProjectIn\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\":\n" +
	"\x0eShowProjectOut\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.project.ViewProjectR\x04item\"\xbd\x02\n" +
	"\x0fCreateProjectIn\x12&\n" +
	"\x0fproject_user_id\x18\x01 \x01(\tR\rprojectUserId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tthumbnail\x18\x04 \x01(\tR\tthumbnail\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x03R\x04cost\x129\n" +
	"\n" +
	"start_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x12C\n" +
	"\x0fcompletion_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\"\x12\n" +
	"\x10CreateProjectOut\"\xb4\x02\n" +
	"\x0fUpdateProjectIn\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tthumbnail\x18\x04 \x01(\tR\tthumbnail\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x03R\x04cost\x129\n" +
	"\n" +
	"start_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x12C\n" +
	"\x0fcompletion_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\"\x12\n" +
	"\x10UpdateProjectOut\"0\n" +
	"\x0fRemoveProjectIn\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x12\n" +
	"\x10RemoveProjectOut\"9\n" +
	"\vViewProject\x12*\n" +
	"\aproject\x18\x01 \x01(\v2\x10.project.ProjectR\aproject\"\xd2\x03\n" +
	"\aProject\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12&\n" +
	"\x0fproject_user_id\x18\x02 \x01(\tR\rprojectUserId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tthumbnail\x18\x05 \x01(\tR\tthumbnail\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x12\n" +
	"\x04cost\x18\a \x01(\x03R\x04cost\x129\n" +
	"\n" +
	"start_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x12C\n" +
	"\x0fcompletion_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12=\n" +
	"\fcreated_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12=\n" +
	"\fupdated_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vupdatedTime2\xe5\x02\n" +
	"\x0eProjectService\x12A\n" +
	"\fShowProjects\x12\x17.project.ShowProjectsIn\x1a\x18.project.ShowProjectsOut\x12>\n" +
	"\vShowProject\x12\x16.project.ShowProjectIn\x1a\x17.project.ShowProjectOut\x12D\n" +
	"\rCreateProject\x12\x18.project.CreateProjectIn\x1a\x19.project.CreateProjectOut\x12D\n" +
	"\rUpdateProject\x12\x18.project.UpdateProjectIn\x1a\x19.project.UpdateProjectOut\x12D\n" +
	"\rRemoveProject\x12\x18.project.RemoveProjectIn\x1a\x19.project.RemoveProjectOutBBZ@github.com/Jmaglinte-Projects/crocsbook-go-app/infra/grpc/protosb\x06proto3"

var (
	file_project_proto_rawDescOnce sync.Once
	file_project_proto_rawDescData []byte
)

func file_project_proto_rawDescGZIP() []byte {
	file_project_proto_rawDescOnce.Do(func() {
		file_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)))
	})
	return file_project_proto_rawDescData
}

var file_project_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_project_proto_goTypes = []any{
	(*ShowProjectsIn)(nil),        // 0: project.ShowProjectsIn
	(*ShowProjectsOut)(nil),       // 1: project.ShowProjectsOut
	(*ShowProjectIn)(nil),         // 2: project.ShowProjectIn
	(*ShowProjectOut)(nil),        // 3: project.ShowProjectOut
	(*CreateProjectIn)(nil),       // 4: project.CreateProjectIn
	(*CreateProjectOut)(nil),      // 5: project.CreateProjectOut
	(*UpdateProjectIn)(nil),       // 6: project.UpdateProjectIn
	(*UpdateProjectOut)(nil),      // 7: project.UpdateProjectOut
	(*RemoveProjectIn)(nil),       // 8: project.RemoveProjectIn
	(*RemoveProjectOut)(nil),      // 9: project.RemoveProjectOut
	(*ViewProject)(nil),           // 10: project.ViewProject
	(*Project)(nil),               // 11: project.Project
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_project_proto_depIdxs = []int32{
	10, // 0: project.ShowProjectsOut.items:type_name -> project.ViewProject
	10, // 1: project.ShowProjectOut.item:type_name -> project.ViewProject
	12, // 2: project.CreateProjectIn.start_date:type_name -> google.protobuf.Timestamp
	12, // 3: project.CreateProjectIn.completion_date:type_name -> google.protobuf.Timestamp
	12, // 4: project.UpdateProjectIn.start_date:type_name -> google.protobuf.Timestamp
	12, // 5: project.UpdateProjectIn.completion_date:type_name -> google.protobuf.Timestamp
	11, // 6: project.ViewProject.project:type_name -> project.Project
	12, // 7: project.Project.start_date:type_name -> google.protobuf.Timestamp
	12, // 8: project.Project.completion_date:type_name -> google.protobuf.Timestamp
	12, // 9: project.Project.created_time:type_name -> google.protobuf.Timestamp
	12, // 10: project.Project.updated_time:type_name -> google.protobuf.Timestamp
	0,  // 11: project.ProjectService.ShowProjects:input_type -> project.ShowProjectsIn
	2,  // 12: project.ProjectService.ShowProject:input_type -> project.ShowProjectIn
	4,  // 13: project.ProjectService.CreateProject:input_type -> project.CreateProjectIn
	6,  // 14: project.ProjectService.UpdateProject:input_type -> project.UpdateProjectIn
	8,  // 15: project.ProjectService.RemoveProject:input_type -> project.RemoveProjectIn
	1,  // 16: project.ProjectService.ShowProjects:output_type -> project.ShowProjectsOut
	3,  // 17: project.ProjectService.ShowProject:output_type -> project.ShowProjectOut
	5,  // 18: project.ProjectService.CreateProject:output_type -> project.CreateProjectOut
	7,  // 19: project.ProjectService.UpdateProject:output_type -> project.UpdateProjectOut
	9,  // 20: project.ProjectService.RemoveProject:output_type -> project.RemoveProjectOut
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_project_proto_init() }
func file_project_proto_init() {
	if File_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_proto_goTypes,
		DependencyIndexes: file_project_proto_depIdxs,
		MessageInfos:      file_project_proto_msgTypes,
	}.Build()
	File_project_proto = out.File
	file_project_proto_goTypes = nil
	file_project_proto_depIdxs = nil
}
