// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: reaction.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReactionType int32

const (
	ReactionType_ReactionType_UNSPECIFIED ReactionType = 0
	ReactionType_ReactionType_LIKE        ReactionType = 1
)

// Enum value maps for ReactionType.
var (
	ReactionType_name = map[int32]string{
		0: "ReactionType_UNSPECIFIED",
		1: "ReactionType_LIKE",
	}
	ReactionType_value = map[string]int32{
		"ReactionType_UNSPECIFIED": 0,
		"ReactionType_LIKE":        1,
	}
)

func (x ReactionType) Enum() *ReactionType {
	p := new(ReactionType)
	*p = x
	return p
}

func (x ReactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_reaction_proto_enumTypes[0].Descriptor()
}

func (ReactionType) Type() protoreflect.EnumType {
	return &file_reaction_proto_enumTypes[0]
}

func (x ReactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReactionType.Descriptor instead.
func (ReactionType) EnumDescriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{0}
}

type ShowReactionsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowReactionsIn) Reset() {
	*x = ShowReactionsIn{}
	mi := &file_reaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowReactionsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowReactionsIn) ProtoMessage() {}

func (x *ShowReactionsIn) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowReactionsIn.ProtoReflect.Descriptor instead.
func (*ShowReactionsIn) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{0}
}

type ShowReactionsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ViewReaction        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowReactionsOut) Reset() {
	*x = ShowReactionsOut{}
	mi := &file_reaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowReactionsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowReactionsOut) ProtoMessage() {}

func (x *ShowReactionsOut) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowReactionsOut.ProtoReflect.Descriptor instead.
func (*ShowReactionsOut) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{1}
}

func (x *ShowReactionsOut) GetItems() []*ViewReaction {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShowReactionsOut) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ShowReactionIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReactionId    string                 `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowReactionIn) Reset() {
	*x = ShowReactionIn{}
	mi := &file_reaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowReactionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowReactionIn) ProtoMessage() {}

func (x *ShowReactionIn) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowReactionIn.ProtoReflect.Descriptor instead.
func (*ShowReactionIn) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{2}
}

func (x *ShowReactionIn) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

type ShowReactionOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Reaction              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowReactionOut) Reset() {
	*x = ShowReactionOut{}
	mi := &file_reaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowReactionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowReactionOut) ProtoMessage() {}

func (x *ShowReactionOut) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowReactionOut.ProtoReflect.Descriptor instead.
func (*ShowReactionOut) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{3}
}

func (x *ShowReactionOut) GetItem() *Reaction {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateReactionIn struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReactionProjectId string                 `protobuf:"bytes,1,opt,name=reaction_project_id,json=reactionProjectId,proto3" json:"reaction_project_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateReactionIn) Reset() {
	*x = CreateReactionIn{}
	mi := &file_reaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReactionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReactionIn) ProtoMessage() {}

func (x *CreateReactionIn) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReactionIn.ProtoReflect.Descriptor instead.
func (*CreateReactionIn) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReactionIn) GetReactionProjectId() string {
	if x != nil {
		return x.ReactionProjectId
	}
	return ""
}

type CreateReactionOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReactionOut) Reset() {
	*x = CreateReactionOut{}
	mi := &file_reaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReactionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReactionOut) ProtoMessage() {}

func (x *CreateReactionOut) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReactionOut.ProtoReflect.Descriptor instead.
func (*CreateReactionOut) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{5}
}

type UpdateReactionIn struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReactionId        string                 `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
	ReactionProjectId string                 `protobuf:"bytes,2,opt,name=reaction_project_id,json=reactionProjectId,proto3" json:"reaction_project_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateReactionIn) Reset() {
	*x = UpdateReactionIn{}
	mi := &file_reaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReactionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReactionIn) ProtoMessage() {}

func (x *UpdateReactionIn) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReactionIn.ProtoReflect.Descriptor instead.
func (*UpdateReactionIn) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReactionIn) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

func (x *UpdateReactionIn) GetReactionProjectId() string {
	if x != nil {
		return x.ReactionProjectId
	}
	return ""
}

type UpdateReactionOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReactionOut) Reset() {
	*x = UpdateReactionOut{}
	mi := &file_reaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReactionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReactionOut) ProtoMessage() {}

func (x *UpdateReactionOut) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReactionOut.ProtoReflect.Descriptor instead.
func (*UpdateReactionOut) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{7}
}

type RemoveReactionIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReactionId    string                 `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReactionIn) Reset() {
	*x = RemoveReactionIn{}
	mi := &file_reaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReactionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReactionIn) ProtoMessage() {}

func (x *RemoveReactionIn) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReactionIn.ProtoReflect.Descriptor instead.
func (*RemoveReactionIn) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveReactionIn) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

type RemoveReactionOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReactionOut) Reset() {
	*x = RemoveReactionOut{}
	mi := &file_reaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReactionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReactionOut) ProtoMessage() {}

func (x *RemoveReactionOut) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReactionOut.ProtoReflect.Descriptor instead.
func (*RemoveReactionOut) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{9}
}

type ViewReaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reaction      *Reaction              `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewReaction) Reset() {
	*x = ViewReaction{}
	mi := &file_reaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewReaction) ProtoMessage() {}

func (x *ViewReaction) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewReaction.ProtoReflect.Descriptor instead.
func (*ViewReaction) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{10}
}

func (x *ViewReaction) GetReaction() *Reaction {
	if x != nil {
		return x.Reaction
	}
	return nil
}

type Reaction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReactionId        string                 `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
	ReactionProjectId string                 `protobuf:"bytes,2,opt,name=reaction_project_id,json=reactionProjectId,proto3" json:"reaction_project_id,omitempty"`
	Type              ReactionType           `protobuf:"varint,3,opt,name=type,proto3,enum=reaction.ReactionType" json:"type,omitempty"`
	CreatedTime       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_reaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{11}
}

func (x *Reaction) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

func (x *Reaction) GetReactionProjectId() string {
	if x != nil {
		return x.ReactionProjectId
	}
	return ""
}

func (x *Reaction) GetType() ReactionType {
	if x != nil {
		return x.Type
	}
	return ReactionType_ReactionType_UNSPECIFIED
}

func (x *Reaction) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

var File_reaction_proto protoreflect.FileDescriptor

const file_reaction_proto_rawDesc = "" +
	"\n" +
	"\x0ereaction.proto\x12\breaction\x1a\x1fgoogle/protobuf/timestamp.proto\"\x11\n" +
	"\x0fShowReactionsIn\"V\n" +
	"\x10ShowReactionsOut\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.reaction.ViewReactionR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"1\n" +
	"\x0eShowReactionIn\x12\x1f\n" +
	"\vreaction_id\x18\x01 \x01(\tR\n" +
	"reactionId\"9\n" +
	"\x0fShowReactionOut\x12&\n" +
	"\x04item\x18\x01 \x01(\v2\x12.reaction.ReactionR\x04item\"B\n" +
	"\x10CreateReactionIn\x12.\n" +
	"\x13reaction_project_id\x18\x01 \x01(\tR\x11reactionProjectId\"\x13\n" +
	"\x11CreateReactionOut\"c\n" +
	"\x10UpdateReactionIn\x12\x1f\n" +
	"\vreaction_id\x18\x01 \x01(\tR\n" +
	"reactionId\x12.\n" +
	"\x13reaction_project_id\x18\x02 \x01(\tR\x11reactionProjectId\"\x13\n" +
	"\x11UpdateReactionOut\"3\n" +
	"\x10RemoveReactionIn\x12\x1f\n" +
	"\vreaction_id\x18\x01 \x01(\tR\n" +
	"reactionId\"\x13\n" +
	"\x11RemoveReactionOut\">\n" +
	"\fViewReaction\x12.\n" +
	"\breaction\x18\x01 \x01(\v2\x12.reaction.ReactionR\breaction\"\xc6\x01\n" +
	"\bReaction\x12\x1f\n" +
	"\vreaction_id\x18\x01 \x01(\tR\n" +
	"reactionId\x12.\n" +
	"\x13reaction_project_id\x18\x02 \x01(\tR\x11reactionProjectId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.reaction.ReactionTypeR\x04type\x12=\n" +
	"\fcreated_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime*C\n" +
	"\fReactionType\x12\x1c\n" +
	"\x18ReactionType_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ReactionType_LIKE\x10\x012\xff\x02\n" +
	"\x0fReactionService\x12F\n" +
	"\rShowReactions\x12\x19.reaction.ShowReactionsIn\x1a\x1a.reaction.ShowReactionsOut\x12C\n" +
	"\fShowReaction\x12\x18.reaction.ShowReactionIn\x1a\x19.reaction.ShowReactionOut\x12I\n" +
	"\x0eCreateReaction\x12\x1a.reaction.CreateReactionIn\x1a\x1b.reaction.CreateReactionOut\x12I\n" +
	"\x0eUpdateReaction\x12\x1a.reaction.UpdateReactionIn\x1a\x1b.reaction.UpdateReactionOut\x12I\n" +
	"\x0eRemoveReaction\x12\x1a.reaction.RemoveReactionIn\x1a\x1b.reaction.RemoveReactionOutBCZAgithub.com/Jmaglinte-Reactions/crocsbook-go-app/infra/grpc/protosb\x06proto3"

var (
	file_reaction_proto_rawDescOnce sync.Once
	file_reaction_proto_rawDescData []byte
)

func file_reaction_proto_rawDescGZIP() []byte {
	file_reaction_proto_rawDescOnce.Do(func() {
		file_reaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reaction_proto_rawDesc), len(file_reaction_proto_rawDesc)))
	})
	return file_reaction_proto_rawDescData
}

var file_reaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reaction_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_reaction_proto_goTypes = []any{
	(ReactionType)(0),             // 0: reaction.ReactionType
	(*ShowReactionsIn)(nil),       // 1: reaction.ShowReactionsIn
	(*ShowReactionsOut)(nil),      // 2: reaction.ShowReactionsOut
	(*ShowReactionIn)(nil),        // 3: reaction.ShowReactionIn
	(*ShowReactionOut)(nil),       // 4: reaction.ShowReactionOut
	(*CreateReactionIn)(nil),      // 5: reaction.CreateReactionIn
	(*CreateReactionOut)(nil),     // 6: reaction.CreateReactionOut
	(*UpdateReactionIn)(nil),      // 7: reaction.UpdateReactionIn
	(*UpdateReactionOut)(nil),     // 8: reaction.UpdateReactionOut
	(*RemoveReactionIn)(nil),      // 9: reaction.RemoveReactionIn
	(*RemoveReactionOut)(nil),     // 10: reaction.RemoveReactionOut
	(*ViewReaction)(nil),          // 11: reaction.ViewReaction
	(*Reaction)(nil),              // 12: reaction.Reaction
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_reaction_proto_depIdxs = []int32{
	11, // 0: reaction.ShowReactionsOut.items:type_name -> reaction.ViewReaction
	12, // 1: reaction.ShowReactionOut.item:type_name -> reaction.Reaction
	12, // 2: reaction.ViewReaction.reaction:type_name -> reaction.Reaction
	0,  // 3: reaction.Reaction.type:type_name -> reaction.ReactionType
	13, // 4: reaction.Reaction.created_time:type_name -> google.protobuf.Timestamp
	1,  // 5: reaction.ReactionService.ShowReactions:input_type -> reaction.ShowReactionsIn
	3,  // 6: reaction.ReactionService.ShowReaction:input_type -> reaction.ShowReactionIn
	5,  // 7: reaction.ReactionService.CreateReaction:input_type -> reaction.CreateReactionIn
	7,  // 8: reaction.ReactionService.UpdateReaction:input_type -> reaction.UpdateReactionIn
	9,  // 9: reaction.ReactionService.RemoveReaction:input_type -> reaction.RemoveReactionIn
	2,  // 10: reaction.ReactionService.ShowReactions:output_type -> reaction.ShowReactionsOut
	4,  // 11: reaction.ReactionService.ShowReaction:output_type -> reaction.ShowReactionOut
	6,  // 12: reaction.ReactionService.CreateReaction:output_type -> reaction.CreateReactionOut
	8,  // 13: reaction.ReactionService.UpdateReaction:output_type -> reaction.UpdateReactionOut
	10, // 14: reaction.ReactionService.RemoveReaction:output_type -> reaction.RemoveReactionOut
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_reaction_proto_init() }
func file_reaction_proto_init() {
	if File_reaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reaction_proto_rawDesc), len(file_reaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reaction_proto_goTypes,
		DependencyIndexes: file_reaction_proto_depIdxs,
		EnumInfos:         file_reaction_proto_enumTypes,
		MessageInfos:      file_reaction_proto_msgTypes,
	}.Build()
	File_reaction_proto = out.File
	file_reaction_proto_goTypes = nil
	file_reaction_proto_depIdxs = nil
}
