// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: reaction.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReactionService_ShowReactions_FullMethodName  = "/reaction.ReactionService/ShowReactions"
	ReactionService_ShowReaction_FullMethodName   = "/reaction.ReactionService/ShowReaction"
	ReactionService_CreateReaction_FullMethodName = "/reaction.ReactionService/CreateReaction"
	ReactionService_UpdateReaction_FullMethodName = "/reaction.ReactionService/UpdateReaction"
	ReactionService_RemoveReaction_FullMethodName = "/reaction.ReactionService/RemoveReaction"
)

// ReactionServiceClient is the client API for ReactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReactionServiceClient interface {
	ShowReactions(ctx context.Context, in *ShowReactionsIn, opts ...grpc.CallOption) (*ShowReactionsOut, error)
	ShowReaction(ctx context.Context, in *ShowReactionIn, opts ...grpc.CallOption) (*ShowReactionOut, error)
	CreateReaction(ctx context.Context, in *CreateReactionIn, opts ...grpc.CallOption) (*CreateReactionOut, error)
	UpdateReaction(ctx context.Context, in *UpdateReactionIn, opts ...grpc.CallOption) (*UpdateReactionOut, error)
	RemoveReaction(ctx context.Context, in *RemoveReactionIn, opts ...grpc.CallOption) (*RemoveReactionOut, error)
}

type reactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReactionServiceClient(cc grpc.ClientConnInterface) ReactionServiceClient {
	return &reactionServiceClient{cc}
}

func (c *reactionServiceClient) ShowReactions(ctx context.Context, in *ShowReactionsIn, opts ...grpc.CallOption) (*ShowReactionsOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowReactionsOut)
	err := c.cc.Invoke(ctx, ReactionService_ShowReactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) ShowReaction(ctx context.Context, in *ShowReactionIn, opts ...grpc.CallOption) (*ShowReactionOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowReactionOut)
	err := c.cc.Invoke(ctx, ReactionService_ShowReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) CreateReaction(ctx context.Context, in *CreateReactionIn, opts ...grpc.CallOption) (*CreateReactionOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReactionOut)
	err := c.cc.Invoke(ctx, ReactionService_CreateReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) UpdateReaction(ctx context.Context, in *UpdateReactionIn, opts ...grpc.CallOption) (*UpdateReactionOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReactionOut)
	err := c.cc.Invoke(ctx, ReactionService_UpdateReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) RemoveReaction(ctx context.Context, in *RemoveReactionIn, opts ...grpc.CallOption) (*RemoveReactionOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveReactionOut)
	err := c.cc.Invoke(ctx, ReactionService_RemoveReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReactionServiceServer is the server API for ReactionService service.
// All implementations must embed UnimplementedReactionServiceServer
// for forward compatibility.
type ReactionServiceServer interface {
	ShowReactions(context.Context, *ShowReactionsIn) (*ShowReactionsOut, error)
	ShowReaction(context.Context, *ShowReactionIn) (*ShowReactionOut, error)
	CreateReaction(context.Context, *CreateReactionIn) (*CreateReactionOut, error)
	UpdateReaction(context.Context, *UpdateReactionIn) (*UpdateReactionOut, error)
	RemoveReaction(context.Context, *RemoveReactionIn) (*RemoveReactionOut, error)
	mustEmbedUnimplementedReactionServiceServer()
}

// UnimplementedReactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReactionServiceServer struct{}

func (UnimplementedReactionServiceServer) ShowReactions(context.Context, *ShowReactionsIn) (*ShowReactionsOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowReactions not implemented")
}
func (UnimplementedReactionServiceServer) ShowReaction(context.Context, *ShowReactionIn) (*ShowReactionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowReaction not implemented")
}
func (UnimplementedReactionServiceServer) CreateReaction(context.Context, *CreateReactionIn) (*CreateReactionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReaction not implemented")
}
func (UnimplementedReactionServiceServer) UpdateReaction(context.Context, *UpdateReactionIn) (*UpdateReactionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReaction not implemented")
}
func (UnimplementedReactionServiceServer) RemoveReaction(context.Context, *RemoveReactionIn) (*RemoveReactionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveReaction not implemented")
}
func (UnimplementedReactionServiceServer) mustEmbedUnimplementedReactionServiceServer() {}
func (UnimplementedReactionServiceServer) testEmbeddedByValue()                         {}

// UnsafeReactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReactionServiceServer will
// result in compilation errors.
type UnsafeReactionServiceServer interface {
	mustEmbedUnimplementedReactionServiceServer()
}

func RegisterReactionServiceServer(s grpc.ServiceRegistrar, srv ReactionServiceServer) {
	// If the following call pancis, it indicates UnimplementedReactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReactionService_ServiceDesc, srv)
}

func _ReactionService_ShowReactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowReactionsIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).ShowReactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReactionService_ShowReactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).ShowReactions(ctx, req.(*ShowReactionsIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_ShowReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowReactionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).ShowReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReactionService_ShowReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).ShowReaction(ctx, req.(*ShowReactionIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_CreateReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReactionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).CreateReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReactionService_CreateReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).CreateReaction(ctx, req.(*CreateReactionIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_UpdateReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReactionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).UpdateReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReactionService_UpdateReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).UpdateReaction(ctx, req.(*UpdateReactionIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_RemoveReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReactionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).RemoveReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReactionService_RemoveReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).RemoveReaction(ctx, req.(*RemoveReactionIn))
	}
	return interceptor(ctx, in, info, handler)
}

// ReactionService_ServiceDesc is the grpc.ServiceDesc for ReactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reaction.ReactionService",
	HandlerType: (*ReactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowReactions",
			Handler:    _ReactionService_ShowReactions_Handler,
		},
		{
			MethodName: "ShowReaction",
			Handler:    _ReactionService_ShowReaction_Handler,
		},
		{
			MethodName: "CreateReaction",
			Handler:    _ReactionService_CreateReaction_Handler,
		},
		{
			MethodName: "UpdateReaction",
			Handler:    _ReactionService_UpdateReaction_Handler,
		},
		{
			MethodName: "RemoveReaction",
			Handler:    _ReactionService_RemoveReaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reaction.proto",
}
