// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: user.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type ShowUsersIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowUsersIn) Reset() {
	*x = ShowUsersIn{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowUsersIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowUsersIn) ProtoMessage() {}

func (x *ShowUsersIn) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowUsersIn.ProtoReflect.Descriptor instead.
func (*ShowUsersIn) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type ShowUsersOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ViewUser            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowUsersOut) Reset() {
	*x = ShowUsersOut{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowUsersOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowUsersOut) ProtoMessage() {}

func (x *ShowUsersOut) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowUsersOut.ProtoReflect.Descriptor instead.
func (*ShowUsersOut) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *ShowUsersOut) GetItems() []*ViewUser {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShowUsersOut) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ShowUserIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowUserIn) Reset() {
	*x = ShowUserIn{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowUserIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowUserIn) ProtoMessage() {}

func (x *ShowUserIn) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowUserIn.ProtoReflect.Descriptor instead.
func (*ShowUserIn) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ShowUserIn) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShowUserOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *User                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowUserOut) Reset() {
	*x = ShowUserOut{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowUserOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowUserOut) ProtoMessage() {}

func (x *ShowUserOut) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowUserOut.ProtoReflect.Descriptor instead.
func (*ShowUserOut) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *ShowUserOut) GetItem() *User {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateUserIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Gender        Gender                 `protobuf:"varint,2,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserIn) Reset() {
	*x = CreateUserIn{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserIn) ProtoMessage() {}

func (x *CreateUserIn) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserIn.ProtoReflect.Descriptor instead.
func (*CreateUserIn) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserIn) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *CreateUserIn) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateUserIn) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserOut) Reset() {
	*x = CreateUserOut{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserOut) ProtoMessage() {}

func (x *CreateUserOut) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserOut.ProtoReflect.Descriptor instead.
func (*CreateUserOut) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

type UpdateUserIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Gender        Gender                 `protobuf:"varint,3,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserIn) Reset() {
	*x = UpdateUserIn{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserIn) ProtoMessage() {}

func (x *UpdateUserIn) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserIn.ProtoReflect.Descriptor instead.
func (*UpdateUserIn) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserIn) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserIn) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *UpdateUserIn) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type UpdateUserOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserOut) Reset() {
	*x = UpdateUserOut{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserOut) ProtoMessage() {}

func (x *UpdateUserOut) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserOut.ProtoReflect.Descriptor instead.
func (*UpdateUserOut) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

type RemoveUserIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserIn) Reset() {
	*x = RemoveUserIn{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserIn) ProtoMessage() {}

func (x *RemoveUserIn) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserIn.ProtoReflect.Descriptor instead.
func (*RemoveUserIn) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveUserIn) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveUserOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserOut) Reset() {
	*x = RemoveUserOut{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserOut) ProtoMessage() {}

func (x *RemoveUserOut) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserOut.ProtoReflect.Descriptor instead.
func (*RemoveUserOut) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

type ViewUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewUser) Reset() {
	*x = ViewUser{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewUser) ProtoMessage() {}

func (x *ViewUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewUser.ProtoReflect.Descriptor instead.
func (*ViewUser) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *ViewUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Gender        Gender                 `protobuf:"varint,3,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	ProfileUrl    string                 `protobuf:"bytes,4,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *User) GetProfileUrl() string {
	if x != nil {
		return x.ProfileUrl
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *User) GetUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTime
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vShowUsersIn\"J\n" +
	"\fShowUsersOut\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.user.ViewUserR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"%\n" +
	"\n" +
	"ShowUserIn\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\vShowUserOut\x12\x1e\n" +
	"\x04item\x18\x01 \x01(\v2\n" +
	".user.UserR\x04item\"\x9e\x01\n" +
	"\fCreateUserIn\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12$\n" +
	"\x06gender\x18\x02 \x01(\x0e2\f.user.GenderR\x06gender\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"\x0f\n" +
	"\rCreateUserOut\"\x7f\n" +
	"\fUpdateUserIn\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12$\n" +
	"\x06gender\x18\x03 \x01(\x0e2\f.user.GenderR\x06gender\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"\x0f\n" +
	"\rUpdateUserOut\"'\n" +
	"\fRemoveUserIn\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x0f\n" +
	"\rRemoveUserOut\"*\n" +
	"\bViewUser\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"\xce\x02\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12$\n" +
	"\x06gender\x18\x03 \x01(\x0e2\f.user.GenderR\x06gender\x12\x1f\n" +
	"\vprofile_url\x18\x04 \x01(\tR\n" +
	"profileUrl\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12=\n" +
	"\fcreated_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12=\n" +
	"\fupdated_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vupdatedTime*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x022\x97\x02\n" +
	"\vUserService\x122\n" +
	"\tShowUsers\x12\x11.user.ShowUsersIn\x1a\x12.user.ShowUsersOut\x12/\n" +
	"\bShowUser\x12\x10.user.ShowUserIn\x1a\x11.user.ShowUserOut\x125\n" +
	"\n" +
	"CreateUser\x12\x12.user.CreateUserIn\x1a\x13.user.CreateUserOut\x125\n" +
	"\n" +
	"UpdateUser\x12\x12.user.UpdateUserIn\x1a\x13.user.UpdateUserOut\x125\n" +
	"\n" +
	"RemoveUser\x12\x12.user.RemoveUserIn\x1a\x13.user.RemoveUserOutB?Z=github.com/Jmaglinte-Users/crocsbook-go-app/infra/grpc/protosb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_user_proto_goTypes = []any{
	(Gender)(0),                   // 0: user.Gender
	(*ShowUsersIn)(nil),           // 1: user.ShowUsersIn
	(*ShowUsersOut)(nil),          // 2: user.ShowUsersOut
	(*ShowUserIn)(nil),            // 3: user.ShowUserIn
	(*ShowUserOut)(nil),           // 4: user.ShowUserOut
	(*CreateUserIn)(nil),          // 5: user.CreateUserIn
	(*CreateUserOut)(nil),         // 6: user.CreateUserOut
	(*UpdateUserIn)(nil),          // 7: user.UpdateUserIn
	(*UpdateUserOut)(nil),         // 8: user.UpdateUserOut
	(*RemoveUserIn)(nil),          // 9: user.RemoveUserIn
	(*RemoveUserOut)(nil),         // 10: user.RemoveUserOut
	(*ViewUser)(nil),              // 11: user.ViewUser
	(*User)(nil),                  // 12: user.User
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	11, // 0: user.ShowUsersOut.items:type_name -> user.ViewUser
	12, // 1: user.ShowUserOut.item:type_name -> user.User
	0,  // 2: user.CreateUserIn.gender:type_name -> user.Gender
	0,  // 3: user.UpdateUserIn.gender:type_name -> user.Gender
	12, // 4: user.ViewUser.user:type_name -> user.User
	0,  // 5: user.User.gender:type_name -> user.Gender
	13, // 6: user.User.created_time:type_name -> google.protobuf.Timestamp
	13, // 7: user.User.updated_time:type_name -> google.protobuf.Timestamp
	1,  // 8: user.UserService.ShowUsers:input_type -> user.ShowUsersIn
	3,  // 9: user.UserService.ShowUser:input_type -> user.ShowUserIn
	5,  // 10: user.UserService.CreateUser:input_type -> user.CreateUserIn
	7,  // 11: user.UserService.UpdateUser:input_type -> user.UpdateUserIn
	9,  // 12: user.UserService.RemoveUser:input_type -> user.RemoveUserIn
	2,  // 13: user.UserService.ShowUsers:output_type -> user.ShowUsersOut
	4,  // 14: user.UserService.ShowUser:output_type -> user.ShowUserOut
	6,  // 15: user.UserService.CreateUser:output_type -> user.CreateUserOut
	8,  // 16: user.UserService.UpdateUser:output_type -> user.UpdateUserOut
	10, // 17: user.UserService.RemoveUser:output_type -> user.RemoveUserOut
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
