//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ChatThreadParticipants struct {
	ChatThreadID      string `sql:"primary_key"`
	UserID            string `sql:"primary_key"`
	ArchivedAt        *time.Time
	MutedAt           *time.Time
	LastReadMessageID *string
	LastReadAt        *time.Time
	JoinedAt          time.Time
	LeftAt            *time.Time
}
