//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ChatMessages struct {
	ChatMessageID string `sql:"primary_key"`
	ChatThreadID  string
	SenderUserID  string
	MessageType   ChatMessagesMessageType
	Body          *string
	CreatedAt     time.Time
	UpdatedAt     *time.Time
	DeletedAt     *time.Time
}
