//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ChatMessageAttachments struct {
	ChatMessageAttachmentID string `sql:"primary_key"`
	ChatMessageID           string
	FileName                string
	FileType                *string
	FileSize                *int64
	R2Bucket                string
	R2ObjectKey             string
	PublicURL               *string
	CreatedAt               time.Time
}
