//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ChatMessagesMessageType string

const (
	ChatMessagesMessageType_Text       ChatMessagesMessageType = "text"
	ChatMessagesMessageType_Image      ChatMessagesMessageType = "image"
	ChatMessagesMessageType_Attachment ChatMessagesMessageType = "attachment"
)

var ChatMessagesMessageTypeAllValues = []ChatMessagesMessageType{
	ChatMessagesMessageType_Text,
	ChatMessagesMessageType_Image,
	ChatMessagesMessageType_Attachment,
}

func (e *ChatMessagesMessageType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "text":
		*e = ChatMessagesMessageType_Text
	case "image":
		*e = ChatMessagesMessageType_Image
	case "attachment":
		*e = ChatMessagesMessageType_Attachment
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ChatMessagesMessageType enum")
	}

	return nil
}

func (e ChatMessagesMessageType) String() string {
	return string(e)
}
