//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ChatThreads struct {
	ChatThreadID  string `sql:"primary_key"`
	Type          ChatThreadsType
	Title         *string
	LastMessageID *string
	LastMessageAt *time.Time
	CreatedAt     time.Time
	UpdatedAt     *time.Time
}
