//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ChatThreadsType string

const (
	ChatThreadsType_Direct ChatThreadsType = "direct"
	ChatThreadsType_Group  ChatThreadsType = "group"
)

var ChatThreadsTypeAllValues = []ChatThreadsType{
	ChatThreadsType_Direct,
	ChatThreadsType_Group,
}

func (e *ChatThreadsType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "direct":
		*e = ChatThreadsType_Direct
	case "group":
		*e = ChatThreadsType_Group
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ChatThreadsType enum")
	}

	return nil
}

func (e ChatThreadsType) String() string {
	return string(e)
}
