//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Medias struct {
	MediaID     string `sql:"primary_key"`
	MediaPostID string `sql:"primary_key"`
	URL         *string
	Type        *MediasType
	CreatedTime time.Time
}
