//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Posts struct {
	PostID        string `sql:"primary_key"`
	PostProjectID string `sql:"primary_key"`
	Content       *string
	Visibility    *PostsVisibility
	CreatedTime   time.Time
	UpdatedTime   *time.Time
}
