//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PostReactionsReactionType string

const (
	PostReactionsReactionType_Like  PostReactionsReactionType = "Like"
	PostReactionsReactionType_Heart PostReactionsReactionType = "Heart"
)

var PostReactionsReactionTypeAllValues = []PostReactionsReactionType{
	PostReactionsReactionType_Like,
	PostReactionsReactionType_Heart,
}

func (e *PostReactionsReactionType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Like":
		*e = PostReactionsReactionType_Like
	case "Heart":
		*e = PostReactionsReactionType_Heart
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PostReactionsReactionType enum")
	}

	return nil
}

func (e PostReactionsReactionType) String() string {
	return string(e)
}
