//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PostComments struct {
	CommentID       string `sql:"primary_key"`
	PostID          string
	UserID          string
	ParentCommentID *string
	Content         string
	CreatedTime     time.Time
	UpdatedTime     *time.Time
}
