//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Projects struct {
	ProjectID      string `sql:"primary_key"`
	ProjectUserID  string `sql:"primary_key"`
	Name           string
	Description    *string
	ThumbnailKey   *string
	Location       *string
	Cost           *int64
	StartDate      *time.Time
	CompletionDate *time.Time
	CreatedTime    time.Time
	UpdatedTime    *time.Time
}
