//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ReactionsType string

const (
	ReactionsType_Like ReactionsType = "Like"
)

var ReactionsTypeAllValues = []ReactionsType{
	ReactionsType_Like,
}

func (e *ReactionsType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Like":
		*e = ReactionsType_Like
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ReactionsType enum")
	}

	return nil
}

func (e ReactionsType) String() string {
	return string(e)
}
