//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Reactions struct {
	ReactionID    string `sql:"primary_key"`
	PostProjectID string `sql:"primary_key"`
	Type          *ReactionsType
	CreatedTime   time.Time
}
