//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	UserID     string `sql:"primary_key"`
	Email      string
	Gender     string
	ProfileURL *string
	Nickname   *string
	Username   *string
	Password   *string
	CreatedAt  time.Time
	UpdatedAt  *time.Time
}
